import { CORRECTION_INSTRUCTIONS, type PositionCorrection } from '@/features/capture-guidance/types';

const englishStrings = {
  'app.settings': 'App settings',
  'camera.allowCamera': 'Allow camera',
  'camera.allowRecording': 'Allow recording',
  'camera.cameraPermission': 'Camera permission',
  'camera.cameraPermissionDetail': 'Camera access is needed to capture task evidence.',
  'camera.capture': 'Capture',
  'camera.audioCapture': 'Audio capture',
  'camera.captureAudio': 'Capture audio',
  'camera.captureChooser': 'Open capture chooser',
  'camera.captureDisabledBy': 'Capture disabled by',
  'camera.captureImage': 'Capture image',
  'camera.captureRequiredMedia': 'Capture required media',
  'camera.captureVideo': 'Capture video',
  'camera.imageCapture': 'Image capture',
  'camera.pickImage': 'Pick image',
  'camera.pickVideo': 'Pick video',
  'camera.recording': 'Recording',
  'camera.recordVideo': 'Record video',
  'camera.recordingPermission': 'Camera and microphone permission',
  'camera.recordingPermissionDetail': 'Camera and microphone access are needed to record task evidence.',
  'camera.secondsCaptured': 'seconds captured',
  'camera.startRecording': 'Start recording',
  'camera.startTask': 'Start Task',
  'camera.startTaskDetail': 'Capture media, review it, and submit through the offline-safe upload queue.',
  'camera.stopAndSave': 'Stop and save',
  'camera.stopRecording': 'Stop recording',
  'camera.taskMedia': 'Task media',
  'camera.videoCapture': 'Video capture',
  'common.automatic': 'Automatic',
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.changeLanguage': 'Change language',
  'common.close': 'Close',
  'common.continue': 'Continue',
  'common.mock': 'mock',
  'common.new': 'new',
  'common.notConfigured': 'Not configured',
  'common.off': 'OFF',
  'common.on': 'ON',
  'common.open': 'Open',
  'common.optional': 'optional',
  'common.pause': 'Pause',
  'common.play': 'Play',
  'common.ready': 'ready',
  'common.required': 'required',
  'common.retry': 'Retry',
  'common.saveAndContinue': 'Save and continue',
  'common.savePreference': 'Save preference',
  'common.selectingSaves': 'Selecting an option saves immediately.',
  'common.start': 'Start',
  'common.upload': 'Upload',
  'contentValidation.checking': 'Checking video...',
  'contentValidation.continueAnyway': 'Continue anyway',
  'contentValidation.match': 'Video matches task',
  'contentValidation.mismatch': 'Video does not match task',
  'contentValidation.mocked': 'Mocked preliminary semantic check',
  'contentValidation.retryRecording': 'Retry recording',
  'contentValidation.uncertain': 'Unable to confidently verify',
  'mediaProtection.acceptSubmission': 'Accept submission',
  'mediaProtection.adminExportOriginal': 'Admin export original',
  'mediaProtection.adminExportReason': 'Reason for original export',
  'mediaProtection.adminOnly': 'Admin only',
  'mediaProtection.auditCreated': 'Audit event created',
  'mediaProtection.exportOriginal': 'Export original without watermark',
  'mediaProtection.mockedBackendJob': 'Mock watermark lifecycle',
  'mediaProtection.privateOriginal': 'Private original',
  'mediaProtection.privateOriginalDetail': 'The clean master remains private and is never exposed as a client storage URL.',
  'mediaProtection.tenantAcceptanceStartsWatermark': 'Tenant acceptance starts mock watermark processing.',
  'mediaProtection.title': 'Accepted-video protection',
  'mediaProtection.visibleAsset': 'Visible asset',
  'mediaProtection.watermarkFailed': 'Watermark failed',
  'mediaProtection.watermarkNotRequired': 'Watermark not required',
  'mediaProtection.watermarkProcessing': 'Watermark processing',
  'mediaProtection.watermarkReady': 'Watermark ready',
  'mediaProtection.watermarkText': 'Watermark text',
  'mediaProtection.workerTenantDerivativeOnly': 'Worker and tenant views use the watermarked derivative after acceptance.',
  'appeals.appeals': 'Appeals',
  'appeals.createAppeal': 'Create appeal',
  'appeals.createAppealDetail': 'Uses submission.appeal. Decisions happen on the backend.',
  'appeals.ground': 'Ground',
  'appeals.recentAppeals': 'Recent appeals',
  'appeals.submissionAppeals': 'Submission appeals',
  'appeals.submissionId': 'Submission ID',
  'appeals.submitAppeal': 'Submit appeal',
  'annotation.annotate': 'Annotate',
  'annotation.confirmedLabel': 'Confirmed label',
  'annotation.edgeAutoLabel': 'Edge Auto-label simulated',
  'annotation.localValidation': 'local validation',
  'annotation.mobileAnnotation': 'Mobile annotation',
  'annotation.notes': 'Notes',
  'annotation.preLabelDetail':
    'Pre-label boxes are editable on mobile. Advanced polygons, keypoints and segmentation stay in the Crowd Visual IDE.',
  'annotation.submitAnnotation': 'Submit annotation',
  'devices.accepted': 'Accepted',
  'devices.assignedDevices': 'Assigned devices',
  'devices.awaitingCustody': 'Awaiting custody acceptance',
  'devices.connection': 'Connection',
  'devices.firmware': 'Firmware',
  'devices.kitCustody': 'Kit custody',
  'devices.offset': 'Offset',
  'devices.pairDevice': 'Pair device',
  'devices.pairDeviceDetail':
    'V1 includes the service boundary for BLE, Wi-Fi Direct, UWB and USB-C pairing. Physical integrations are not claimed as working until tested with actual kit hardware.',
  'devices.sync': 'Sync',
  'devices.syncStatus': 'Sync status',
  'devices.custodyDetail': 'Backend custody history remains authoritative.',
  'guidance.label.hold_steady': 'Hold steady',
  'guidance.label.improve_light': 'Improve light',
  'guidance.label.move_closer': 'Move closer',
  'guidance.label.move_down': 'Lower camera',
  'guidance.label.move_farther': 'Move farther',
  'guidance.label.move_left': 'Move left',
  'guidance.label.move_right': 'Move right',
  'guidance.label.move_up': 'Raise camera',
  'guidance.label.ready': 'Ready',
  'guidance.label.straighten': 'Straighten',
  'guidance.label.wait_for_focus': 'Wait for focus',
  'home.clips': 'Clips',
  'home.copilotDetail': 'Local deterministic guidance shell. Ask what is next, why readiness is blocked, or why QC rejected a submission.',
  'home.copilotTitle': 'Edge Copilot',
  'home.earningsLedger': 'Earnings from worker ledger',
  'home.edgePipeline': 'Edge pipeline',
  'home.edgePipelineDetail': 'Edge AI integrations are simulated unless a real provider is configured.',
  'home.greeting': 'Hi',
  'home.jobQueue': 'Job queue',
  'home.jobQueueDetail': 'Available/current jobs from the worker API.',
  'home.labels': 'Labels',
  'home.mockApi': 'Mock API',
  'home.qcExplanation': 'QC explanation',
  'home.queue': 'Queue',
  'home.readinessBlocker': 'Readiness blocker',
  'home.today': 'Today',
  'home.units': 'Units',
  'home.whatsNext': "What's next?",
  'languageRegion.accountScope': 'These preferences stay with your account across personas.',
  'languageRegion.changeLanguage': 'Change Language',
  'languageRegion.changeRegion': 'Change Region',
  'languageRegion.chooseLanguage': 'Choose your language',
  'languageRegion.chooseRegion': 'Choose your region',
  'languageRegion.chooseAppLanguage': 'Choose app language',
  'languageRegion.chooseWorkingRegion': 'Choose working country or region',
  'languageRegion.emptyLanguages': 'No languages found.',
  'languageRegion.emptyRegions': 'No regions found.',
  'languageRegion.explicitChoice': 'You still need to explicitly choose and save your preference.',
  'languageRegion.firstLoginSetup': 'First login setup',
  'languageRegion.language': 'Language',
  'languageRegion.languageRequired': 'Language required',
  'languageRegion.region': 'Region',
  'languageRegion.regionRequired': 'Region required',
  'languageRegion.searchLanguages': 'Search languages',
  'languageRegion.searchRegions': 'Search countries and regions',
  'languageRegion.selectLanguageDetail': 'Select the language you want to use in Cosaarthi.',
  'languageRegion.selectRegionDetail': 'Select your working country or region. We will not infer it from GPS.',
  'languageRegion.suggestedFromDevice': 'Suggested from device',
  'languageRegion.title': 'Language & Region',
  'languageRegion.voiceAutomatic': 'Automatic best available TTS voice',
  'languageRegion.voiceLocaleDetail': 'Camera positioning prompts use',
  'learn.certificationDetail': 'Certification status is part of the readiness gate.',
  'learn.certifications': 'Certifications',
  'learn.complete': 'complete',
  'learn.continueTraining': 'Continue',
  'learn.expires': 'Expires',
  'learn.startTraining': 'Start',
  'learn.title': 'Training and certifications',
  'learn.trainingDetail': 'Required learning gates Capture readiness.',
  'learn.trainingModules': 'Training modules',
  'login.assignedByBackend': 'Assigned by backend after sign in',
  'login.choosePersona': 'Choose Persona',
  'login.demoPassword': 'Demo password',
  'login.demoRolePicker': 'Demo-only role picker',
  'login.email': 'Email',
  'login.mockApiLogin': 'Mock API login',
  'login.password': 'Password',
  'login.persona': 'Persona',
  'login.personaSelector': 'Persona selector',
  'login.signIn': 'Sign in',
  'login.signInToContinue': 'Sign in to continue',
  'login.welcome': 'Welcome to Cosaarthi',
  'profile.about': 'About',
  'profile.aboutDetail': 'Cosaarthi Mobile demo shell',
  'profile.account': 'Account',
  'profile.accountStatus': 'Account status',
  'profile.active': 'Active',
  'profile.activeRole': 'Active role',
  'profile.assignedKit': 'Assigned kit',
  'profile.certificationStatus': 'Certification status',
  'profile.certified': 'certified',
  'profile.chooseLanguageRegion': 'Choose language and region',
  'profile.email': 'Email',
  'profile.entityId': 'Entity ID',
  'profile.entityType': 'Entity type',
  'profile.expired': 'Expired',
  'profile.help': 'Help & Support',
  'profile.helpDetail': 'Support channels are backend-connected in production.',
  'profile.logout': 'Log out',
  'profile.logoutAction': 'Log Out',
  'profile.logoutMessage': 'Are you sure you want to log out?',
  'profile.logoutTitle': 'Log out?',
  'profile.organization': 'Organization',
  'profile.phone': 'Phone',
  'profile.preferences': 'Preferences',
  'profile.profile': 'Profile',
  'profile.roleScope': 'Role scope',
  'profile.settingsDetail': 'App, session, offline queue and localization controls',
  'profile.status': 'status',
  'profile.support': 'Support',
  'profile.tenant': 'Tenant',
  'profile.tenantId': 'Tenant ID',
  'profile.userId': 'User ID',
  'profile.voiceGuidance': 'Voice Guidance',
  'profile.workerId': 'Worker ID',
  'qc.blocked': 'blocked',
  'qc.confidence': 'confidence',
  'qc.detail': 'Local positioning checks guide capture; final QC comes from the backend.',
  'qc.indicators': 'Cosaarthi QC indicators',
  'qc.localFallback': 'Local positioning fallback',
  'readiness.blocked': 'blocked',
  'readiness.detail': 'Capture is disabled when a mandatory Cosaarthi requirement fails.',
  'readiness.gate': 'Readiness Gate',
  'readiness.ready': 'ready',
  'role.actions': 'Actions',
  'role.actionsDetail': 'Enabled controls mutate shared in-memory demo state. Backend-only controls stay disabled.',
  'role.backendUnavailable': 'backend unavailable',
  'role.copilot': 'Copilot',
  'role.copilotDetail': 'Persona-aware prompts from the reference workflow, shown as guidance only.',
  'role.demoShell': 'Demo shell',
  'role.demoState': 'demo state',
  'role.demoUser': 'Demo user',
  'role.hiddenByRbac': 'hidden by RBAC',
  'role.mockedOnly': 'Mocked only',
  'role.navigation': 'Navigation',
  'role.navigationDetail': 'Reference navigation from the Cosaarthi prototype. Mobile opens shells only where backend screens do not exist.',
  'role.notSignedIn': 'Not signed in',
  'role.roleScope': 'Role Scope',
  'role.roleScopeDetail': 'Visible capabilities are filtered by persona permissions and current Cosaarthi role scope.',
  'role.roleSwitcher': 'Role switcher',
  'role.runDemoAction': 'Run demo action',
  'role.session': 'session',
  'role.switchAccount': 'Switch account',
  'role.switcherDetail': 'Same demo account, preserved SecureStore session.',
  'role.worklist': 'Worklist',
  'settings.backendMode': 'Backend mode',
  'settings.languageRegion': 'Language & Region',
  'settings.languageRegionDetail': 'Change app language, region and camera guidance voice.',
  'settings.largeTouchTargets': 'Large touch targets',
  'settings.largeTouchTargetsDetail': 'Controls stay at 48px minimum height.',
  'settings.mockApiAdapter': 'Mock API adapter',
  'settings.notConfigured': 'Not configured',
  'settings.offlineQueue': 'Offline queue',
  'settings.offlineQueueDetail': 'Upload metadata persists in Expo SQLite.',
  'settings.sessionStorage': 'Session storage',
  'settings.sessionStorageDetail': 'Access and refresh tokens are stored in Expo SecureStore.',
  'settings.voiceAutomatic': 'TTS voice: automatic best available voice for the locale.',
  'settings.voiceGuidance': 'Voice Guidance',
  'settings.voiceGuidanceDetail': 'Speak positioning corrections during camera capture in',
  'tabs.devices': 'Devices',
  'tabs.home': 'Home',
  'tabs.learn': 'Learn',
  'tabs.wallet': 'Wallet',
  'tabs.work': 'Work',
  'notifications.allClear': 'All clear',
  'notifications.markAllRead': 'Mark all read',
  'notifications.markRead': 'Mark read',
  'notifications.noAlerts': 'No alerts right now.',
  'notifications.notifications': 'Notifications',
  'notifications.workerAlerts': 'Worker alerts',
  'rating.accuracy': 'accuracy',
  'rating.helpfulness': 'helpfulness',
  'rating.justification': 'Justification',
  'rating.optionA': 'Option A',
  'rating.optionAText': 'Use the visible shelf label and aisle context to classify the product family.',
  'rating.optionB': 'Option B',
  'rating.optionBText': 'Guess the product from the nearest logo and mark the rest as uncertain.',
  'rating.preference': 'Preference',
  'rating.rate': 'Rate',
  'rating.rubric': 'Rubric',
  'rating.safety': 'safety',
  'rating.sideBySideRating': 'Side-by-side rating',
  'rating.submitRating': 'Submit rating',
  'rating.tie': 'tie',
  'survey.assetId': 'Asset ID',
  'survey.autoQcPhotoAttached': 'auto-QC photo attached',
  'survey.autoQcPhotoPending': 'auto-QC photo pending',
  'survey.condition': 'Condition',
  'survey.condition.damaged': 'damaged',
  'survey.condition.good': 'good',
  'survey.condition.missing': 'missing',
  'survey.condition.unsafe': 'unsafe',
  'survey.conditionSurvey': 'Condition survey',
  'survey.observation': 'Observation',
  'survey.photo': 'Photo',
  'survey.qrRackDetail': 'V1 supports typed identifiers and can swap in barcode scanning when the production device service is enabled.',
  'survey.qrRackIdentifier': 'QR / rack identifier',
  'survey.submitSurvey': 'Submit survey',
  'survey.survey': 'Survey',
  'task.due': 'Due',
  'task.checklist': 'Checklist',
  'task.category': 'Category',
  'task.fallbackTitle': 'Task',
  'task.mockReward': 'Mock reward',
  'task.min': 'min',
  'task.open': 'Open',
  'task.openWorkflow': 'Open workflow',
  'task.progress': 'Progress',
  'task.requiredDuration': 'Required duration',
  'task.requirements': 'Requirements',
  'task.qualityBar': 'Quality bar',
  'task.requires': 'Requires',
  'task.remote': 'Remote',
  'task.startCapture': 'Start capture',
  'task.taskPayout': 'Task payout',
  'transcription.audioSegment': 'Audio segment 00:00-00:15',
  'transcription.audioTranscription': 'Audio transcription',
  'transcription.edgePreTranscription': 'Edge pre-transcription simulated',
  'transcription.edgePreTranscriptionDetail': 'Edge pre-transcription is simulated. Do not infer final WER until the backend returns it.',
  'transcription.segmentContext': 'Segment context',
  'transcription.submitTranscription': 'Submit transcription',
  'transcription.transcribe': 'Transcribe',
  'transcription.transcript': 'Transcript',
  'uploads.appealResult': 'Appeal result',
  'uploads.attempt': 'attempt',
  'uploads.backendProcessing': 'The mock review flow is still processing this demo submission.',
  'uploads.defaultProgressMessage': 'Uploading through the local mock Cosaarthi adapter.',
  'uploads.duplicateScore': 'Duplicate score',
  'uploads.failed': 'Failed',
  'uploads.itemNotFound': 'Upload item not found.',
  'uploads.mockDuplicateCheck': 'Demo duplicate check',
  'uploads.mockQcCheck': 'Mock QC check',
  'uploads.mediaPreview': 'Media preview',
  'uploads.notFound': 'Upload not found.',
  'uploads.queueClear': 'Queue is clear',
  'uploads.queueClearDetail': 'Captured files are stored locally and appear here before they sync to the Cosaarthi backend.',
  'uploads.queued': 'Queued',
  'uploads.retryUpload': 'Retry upload',
  'uploads.submissionResult': 'Submission result',
  'uploads.submittedForReview': 'Submitted for review',
  'uploads.submittedForReviewDetail': 'Your video was uploaded successfully. The demo duplicate check flagged it for review.',
  'uploads.title': 'Uploads',
  'uploads.status.accepted': 'Accepted',
  'uploads.status.completed': 'Completed',
  'uploads.status.duplicate': 'Duplicate',
  'uploads.status.failed': 'Failed',
  'uploads.status.pending': 'Pending',
  'uploads.status.possibleDuplicate': 'Possible duplicate',
  'uploads.status.processing': 'Processing',
  'uploads.status.queued': 'Queued',
  'uploads.status.rejected': 'Rejected',
  'uploads.status.uploaded': 'Uploaded',
  'uploads.status.uploading': 'Uploading',
  'uploads.uploadProgress': 'Upload progress',
  'uploads.uploadQueue': 'Upload queue',
  'uploads.uploading': 'Uploading',
  'uploads.viewSubmission': 'View Submission',
  'uploads.backToWork': 'Back to Work',
  'uploads.viewResult': 'View result',
  'validation.addJustification': 'Add a clear justification',
  'validation.addLabel': 'Add a label before submitting',
  'validation.addObservation': 'Add a short observation',
  'validation.amountAboveLimit': 'Amount is above the V1 limit',
  'validation.contextShort': 'Keep context short',
  'validation.enterAssetId': 'Enter a rack or asset identifier',
  'validation.enterSubmissionId': 'Enter a submission ID',
  'validation.explainAppeal': 'Explain why QA should review this submission',
  'validation.minWithdrawal': 'Minimum withdrawal is 100',
  'validation.notesUnderLimit': 'Keep notes under 280 characters',
  'validation.passwordMin': 'Password must be at least 4 characters',
  'validation.transcriptShort': 'Transcript is too short',
  'validation.validEmail': 'Enter a valid email',
  'validation.wholeAmount': 'Enter a whole amount',
  'wallet.amount': 'Amount',
  'wallet.availableBalance': 'Available balance',
  'wallet.earnings': 'Earnings',
  'wallet.earningsByJobType': 'Earnings by job type',
  'wallet.earningsByJobTypeDetail': 'Balance is derived from the server earning ledger.',
  'wallet.ledger': 'Ledger',
  'wallet.lifetime': 'Lifetime',
  'wallet.pending': 'Pending',
  'wallet.requestWithdrawal': 'Request withdrawal',
  'wallet.thisWeek': 'This week',
  'wallet.title': 'Wallet',
  'wallet.withdraw': 'Withdraw',
  'wallet.withdrawDetail': 'Uses wallet.withdraw and does not fake settlement.',
  'wallet.withdrawalActivity': 'Withdrawal activity',
  'work.annotate': 'Annotate',
  'work.annotationDetail': 'Confirm lightweight boxes and labels supplied by Edge Auto-label.',
  'work.annotationTitle': 'Annotation work',
  'work.blockedBy': 'Capture is blocked by',
  'work.capture': 'Capture',
  'work.captureBlockedDetail': 'Capture opens only when mandatory readiness checks pass.',
  'work.captureDetail': 'Camera, image, video and audio collection with local QC guidance.',
  'work.captureTitle': 'Capture work',
  'work.modeTitle': 'Cosaarthi work modes',
  'work.noTasks': 'No tasks',
  'work.noTasksDetail': 'New Cosaarthi work appears here when tenant QA opens more slots.',
  'work.rate': 'Rate',
  'work.rateDetail': 'Side-by-side model evaluation with preference, rubric and justification.',
  'work.rateTitle': 'Rate work',
  'work.submissionDetail': 'Uses submission.create.',
  'work.survey': 'Survey',
  'work.surveyDetail': 'Submit QR, rack or asset condition surveys with auto-QC photo context.',
  'work.surveyTitle': 'Survey work',
  'work.transcribe': 'Transcribe',
  'work.transcriptionDetail': 'Review audio with progress UI and submit editable transcripts.',
  'work.transcriptionTitle': 'Transcription work',
} as const;

export type StringKey = keyof typeof englishStrings;

const strings: Partial<Record<string, Partial<Record<StringKey, string>>>> = {
  ar: {
    'app.settings': 'إعدادات التطبيق',
    'camera.allowCamera': 'السماح بالكاميرا',
    'camera.allowRecording': 'السماح بالتسجيل',
    'camera.cameraPermission': 'إذن الكاميرا',
    'camera.capture': 'التقاط',
    'camera.captureImage': 'التقاط صورة',
    'camera.captureVideo': 'تسجيل فيديو',
    'camera.imageCapture': 'التقاط صورة',
    'camera.pickImage': 'اختيار صورة',
    'camera.pickVideo': 'اختيار فيديو',
    'camera.recordVideo': 'تسجيل فيديو',
    'camera.stopRecording': 'إيقاف التسجيل',
    'common.automatic': 'تلقائي',
    'common.back': 'رجوع',
    'common.cancel': 'إلغاء',
    'common.notConfigured': 'غير مضبوط',
    'common.off': 'إيقاف',
    'common.on': 'تشغيل',
    'common.open': 'فتح',
    'common.optional': 'اختياري',
    'common.ready': 'جاهز',
    'common.required': 'مطلوب',
    'common.saveAndContinue': 'حفظ ومتابعة',
    'common.savePreference': 'حفظ التفضيل',
    'devices.assignedDevices': 'الأجهزة المخصصة',
    'devices.awaitingCustody': 'بانتظار قبول العهدة',
    'devices.kitCustody': 'عهدة المجموعة',
    'devices.pairDevice': 'إقران جهاز',
    'guidance.label.hold_steady': 'ثبّت الهاتف',
    'guidance.label.improve_light': 'حسّن الإضاءة',
    'guidance.label.move_closer': 'اقترب',
    'guidance.label.move_down': 'اخفض الكاميرا',
    'guidance.label.move_farther': 'ابتعد',
    'guidance.label.move_left': 'تحرك يسارًا',
    'guidance.label.move_right': 'تحرك يمينًا',
    'guidance.label.move_up': 'ارفع الكاميرا',
    'guidance.label.ready': 'جاهز',
    'guidance.label.straighten': 'قم بالتسوية',
    'guidance.label.wait_for_focus': 'انتظر التركيز',
    'home.clips': 'مقاطع',
    'home.edgePipeline': 'مسار الحافة',
    'home.greeting': 'مرحبًا',
    'home.jobQueue': 'قائمة الأعمال',
    'home.labels': 'تسميات',
    'home.queue': 'الطابور',
    'home.today': 'اليوم',
    'home.units': 'وحدات',
    'languageRegion.changeLanguage': 'تغيير اللغة',
    'languageRegion.changeRegion': 'تغيير المنطقة',
    'languageRegion.chooseLanguage': 'اختر لغتك',
    'languageRegion.chooseRegion': 'اختر منطقتك',
    'languageRegion.firstLoginSetup': 'إعداد أول تسجيل دخول',
    'languageRegion.language': 'اللغة',
    'languageRegion.region': 'المنطقة',
    'languageRegion.title': 'اللغة والمنطقة',
    'languageRegion.voiceAutomatic': 'أفضل صوت TTS متاح تلقائيًا',
    'learn.certifications': 'الشهادات',
    'learn.title': 'التدريب والشهادات',
    'learn.trainingModules': 'وحدات التدريب',
    'login.choosePersona': 'اختر الشخصية',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.persona': 'الشخصية',
    'login.signIn': 'تسجيل الدخول',
    'login.signInToContinue': 'سجّل الدخول للمتابعة',
    'login.welcome': 'مرحبًا بك في Cosaarthi',
    'profile.account': 'الحساب',
    'profile.accountStatus': 'حالة الحساب',
    'profile.active': 'نشط',
    'profile.email': 'البريد الإلكتروني',
    'profile.help': 'المساعدة والدعم',
    'profile.logout': 'تسجيل الخروج',
    'profile.logoutAction': 'تسجيل الخروج',
    'profile.logoutMessage': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'profile.logoutTitle': 'تسجيل الخروج؟',
    'profile.organization': 'المؤسسة',
    'profile.phone': 'الهاتف',
    'profile.preferences': 'التفضيلات',
    'profile.profile': 'الملف الشخصي',
    'profile.certified': 'معتمد',
    'profile.support': 'الدعم',
    'profile.userId': 'معرّف المستخدم',
    'profile.voiceGuidance': 'الإرشاد الصوتي',
    'qc.blocked': 'محظور',
    'qc.confidence': 'الثقة',
    'qc.indicators': 'مؤشرات فحص Cosaarthi',
    'readiness.blocked': 'محظور',
    'readiness.gate': 'بوابة الجاهزية',
    'readiness.ready': 'جاهز',
    'role.actions': 'الإجراءات',
    'role.demoShell': 'واجهة تجريبية',
    'role.mockedOnly': 'محاكاة فقط',
    'role.navigation': 'التنقل',
    'role.roleScope': 'نطاق الدور',
    'role.roleSwitcher': 'مبدّل الأدوار',
    'role.runDemoAction': 'تشغيل إجراء تجريبي',
    'role.switchAccount': 'تبديل الحساب',
    'role.worklist': 'قائمة العمل',
    'settings.languageRegion': 'اللغة والمنطقة',
    'settings.languageRegionDetail': 'تغيير لغة التطبيق والمنطقة وصوت الإرشادات.',
    'settings.voiceGuidance': 'الإرشاد الصوتي',
    'tabs.devices': 'الأجهزة',
    'tabs.home': 'الرئيسية',
    'tabs.learn': 'التعلم',
    'tabs.wallet': 'المحفظة',
    'tabs.work': 'العمل',
    'task.due': 'الموعد',
    'task.open': 'فتح',
    'task.progress': 'التقدم',
    'uploads.failed': 'فشل',
    'uploads.queued': 'في الطابور',
    'uploads.title': 'التحميلات',
    'uploads.uploading': 'جارٍ الرفع',
    'wallet.amount': 'المبلغ',
    'wallet.availableBalance': 'الرصيد المتاح',
    'wallet.ledger': 'السجل',
    'wallet.pending': 'معلق',
    'wallet.requestWithdrawal': 'طلب سحب',
    'wallet.title': 'المحفظة',
    'wallet.withdraw': 'سحب',
    'work.capture': 'التقاط',
    'work.modeTitle': 'أنماط عمل Cosaarthi',
    'work.noTasks': 'لا توجد مهام',
    'work.rate': 'تقييم',
    'work.survey': 'استبيان',
    'work.transcribe': 'تفريغ',
  },
  es: {
    'app.settings': 'Configuración',
    'camera.allowCamera': 'Permitir cámara',
    'camera.allowRecording': 'Permitir grabación',
    'camera.cameraPermission': 'Permiso de cámara',
    'camera.cameraPermissionDetail': 'Se necesita acceso a la cámara para capturar evidencia de la tarea.',
    'camera.capture': 'Capturar',
    'camera.captureImage': 'Capturar imagen',
    'camera.captureVideo': 'Capturar video',
    'camera.imageCapture': 'Captura de imagen',
    'camera.pickImage': 'Elegir imagen',
    'camera.pickVideo': 'Elegir video',
    'camera.recordVideo': 'Grabar video',
    'camera.recordingPermission': 'Permiso de cámara y micrófono',
    'camera.recordingPermissionDetail': 'Se necesitan cámara y micrófono para grabar evidencia de la tarea.',
    'camera.stopRecording': 'Detener grabación',
    'camera.videoCapture': 'Captura de video',
    'common.automatic': 'Automático',
    'common.back': 'Atrás',
    'common.cancel': 'Cancelar',
    'common.mock': 'simulado',
    'common.notConfigured': 'No configurado',
    'common.off': 'APAGADO',
    'common.on': 'ENCENDIDO',
    'common.open': 'Abrir',
    'common.optional': 'opcional',
    'common.ready': 'listo',
    'common.required': 'obligatorio',
    'common.saveAndContinue': 'Guardar y continuar',
    'common.savePreference': 'Guardar preferencia',
    'common.selectingSaves': 'Seleccionar una opción guarda inmediatamente.',
    'devices.accepted': 'Aceptado',
    'devices.assignedDevices': 'Dispositivos asignados',
    'devices.awaitingCustody': 'Esperando aceptación de custodia',
    'devices.connection': 'Conexión',
    'devices.firmware': 'Firmware',
    'devices.kitCustody': 'Custodia del kit',
    'devices.offset': 'Desfase',
    'devices.pairDevice': 'Emparejar dispositivo',
    'devices.sync': 'Sincronización',
    'devices.syncStatus': 'Estado de sincronización',
    'devices.custodyDetail': 'El historial de custodia del backend sigue siendo la fuente oficial.',
    'guidance.label.hold_steady': 'Mantén estable',
    'guidance.label.improve_light': 'Mejora la luz',
    'guidance.label.move_closer': 'Acércate',
    'guidance.label.move_down': 'Baja la cámara',
    'guidance.label.move_farther': 'Aléjate',
    'guidance.label.move_left': 'Muévete a la izquierda',
    'guidance.label.move_right': 'Muévete a la derecha',
    'guidance.label.move_up': 'Sube la cámara',
    'guidance.label.ready': 'Listo',
    'guidance.label.straighten': 'Endereza',
    'guidance.label.wait_for_focus': 'Espera el enfoque',
    'home.clips': 'Clips',
    'home.copilotDetail': 'Guía determinista local. Pregunta qué sigue, por qué la preparación está bloqueada o por qué QC rechazó un envío.',
    'home.copilotTitle': 'Copiloto Edge',
    'home.earningsLedger': 'Ganancias del libro del trabajador',
    'home.edgePipeline': 'Canal Edge',
    'home.edgePipelineDetail': 'Las integraciones Edge AI se simulan salvo que haya un proveedor real configurado.',
    'home.greeting': 'Hola',
    'home.jobQueue': 'Cola de trabajos',
    'home.jobQueueDetail': 'Trabajos disponibles/actuales desde la API del trabajador.',
    'home.labels': 'Etiquetas',
    'home.mockApi': 'API simulada',
    'home.qcExplanation': 'Explicación QC',
    'home.queue': 'Cola',
    'home.readinessBlocker': 'Bloqueo de preparación',
    'home.today': 'Hoy',
    'home.units': 'Unidades',
    'home.whatsNext': '¿Qué sigue?',
    'languageRegion.accountScope': 'Estas preferencias permanecen con tu cuenta en todas las personas.',
    'languageRegion.changeLanguage': 'Cambiar idioma',
    'languageRegion.changeRegion': 'Cambiar región',
    'languageRegion.chooseLanguage': 'Elige tu idioma',
    'languageRegion.chooseRegion': 'Elige tu región',
    'languageRegion.chooseAppLanguage': 'Elegir idioma de la app',
    'languageRegion.chooseWorkingRegion': 'Elegir país o región de trabajo',
    'languageRegion.emptyLanguages': 'No se encontraron idiomas.',
    'languageRegion.emptyRegions': 'No se encontraron regiones.',
    'languageRegion.explicitChoice': 'Aún debes elegir y guardar explícitamente tu preferencia.',
    'languageRegion.firstLoginSetup': 'Configuración inicial',
    'languageRegion.language': 'Idioma',
    'languageRegion.languageRequired': 'Idioma obligatorio',
    'languageRegion.region': 'Región',
    'languageRegion.regionRequired': 'Región obligatoria',
    'languageRegion.searchLanguages': 'Buscar idiomas',
    'languageRegion.searchRegions': 'Buscar países y regiones',
    'languageRegion.selectLanguageDetail': 'Selecciona el idioma que quieres usar en Cosaarthi.',
    'languageRegion.selectRegionDetail': 'Selecciona tu país o región de trabajo. No lo inferiremos por GPS.',
    'languageRegion.suggestedFromDevice': 'Sugerido por el dispositivo',
    'languageRegion.title': 'Idioma y región',
    'languageRegion.voiceAutomatic': 'Mejor voz TTS disponible automáticamente',
    'languageRegion.voiceLocaleDetail': 'Las indicaciones de posicionamiento usan',
    'learn.certificationDetail': 'El estado de certificación forma parte de la puerta de preparación.',
    'learn.certifications': 'Certificaciones',
    'learn.complete': 'completo',
    'learn.expires': 'Vence',
    'learn.title': 'Capacitación y certificaciones',
    'learn.trainingDetail': 'El aprendizaje requerido habilita la preparación de Captura.',
    'learn.trainingModules': 'Módulos de capacitación',
    'login.assignedByBackend': 'Asignado por el backend después de iniciar sesión',
    'login.choosePersona': 'Elegir persona',
    'login.demoPassword': 'Contraseña demo',
    'login.demoRolePicker': 'Selector de rol solo demo',
    'login.email': 'Email',
    'login.mockApiLogin': 'Inicio con API simulada',
    'login.password': 'Contraseña',
    'login.persona': 'Persona',
    'login.signIn': 'Iniciar sesión',
    'login.signInToContinue': 'Inicia sesión para continuar',
    'login.welcome': 'Bienvenido a Cosaarthi',
    'profile.account': 'Cuenta',
    'profile.accountStatus': 'Estado de la cuenta',
    'profile.active': 'Activa',
    'profile.activeRole': 'Rol activo',
    'profile.assignedKit': 'Kit asignado',
    'profile.certificationStatus': 'Estado de certificación',
    'profile.certified': 'certificadas',
    'profile.chooseLanguageRegion': 'Elegir idioma y región',
    'profile.email': 'Email',
    'profile.entityId': 'ID de entidad',
    'profile.entityType': 'Tipo de entidad',
    'profile.expired': 'Expirada',
    'profile.help': 'Ayuda y soporte',
    'profile.helpDetail': 'Los canales de soporte se conectan al backend en producción.',
    'profile.logout': 'Cerrar sesión',
    'profile.logoutAction': 'Cerrar sesión',
    'profile.logoutMessage': '¿Seguro que quieres cerrar sesión?',
    'profile.logoutTitle': '¿Cerrar sesión?',
    'profile.organization': 'Organización',
    'profile.phone': 'Teléfono',
    'profile.preferences': 'Preferencias',
    'profile.profile': 'Perfil',
    'profile.roleScope': 'Alcance del rol',
    'profile.settingsDetail': 'Controles de app, sesión, cola sin conexión y localización',
    'profile.status': 'estado',
    'profile.support': 'Soporte',
    'profile.tenant': 'Tenant',
    'profile.tenantId': 'ID de tenant',
    'profile.userId': 'ID de usuario',
    'profile.voiceGuidance': 'Guía por voz',
    'profile.workerId': 'ID de trabajador',
    'qc.blocked': 'bloqueado',
    'qc.confidence': 'confianza',
    'qc.detail': 'Las comprobaciones locales guían la captura; el QC final viene del backend.',
    'qc.indicators': 'Indicadores QC de Cosaarthi',
    'qc.localFallback': 'Posicionamiento local',
    'readiness.blocked': 'bloqueado',
    'readiness.detail': 'Captura se desactiva cuando falla un requisito obligatorio de Cosaarthi.',
    'readiness.gate': 'Puerta de preparación',
    'readiness.ready': 'listo',
    'role.actions': 'Acciones',
    'role.demoShell': 'Shell demo',
    'role.mockedOnly': 'Solo simulado',
    'role.navigation': 'Navegación',
    'role.roleScope': 'Alcance del rol',
    'role.roleSwitcher': 'Selector de rol',
    'role.runDemoAction': 'Ejecutar acción demo',
    'role.switchAccount': 'Cambiar cuenta',
    'role.worklist': 'Lista de trabajo',
    'settings.backendMode': 'Modo backend',
    'settings.languageRegion': 'Idioma y región',
    'settings.languageRegionDetail': 'Cambia el idioma, la región y la voz de la guía.',
    'settings.largeTouchTargets': 'Objetivos táctiles grandes',
    'settings.largeTouchTargetsDetail': 'Los controles se mantienen con altura mínima de 48 px.',
    'settings.mockApiAdapter': 'Adaptador API simulado',
    'settings.notConfigured': 'No configurado',
    'settings.offlineQueue': 'Cola sin conexión',
    'settings.offlineQueueDetail': 'Los metadatos de carga persisten en Expo SQLite.',
    'settings.sessionStorage': 'Almacenamiento de sesión',
    'settings.sessionStorageDetail': 'Los tokens se almacenan en Expo SecureStore.',
    'settings.voiceAutomatic': 'Voz TTS: mejor voz automática para el locale.',
    'settings.voiceGuidance': 'Guía por voz',
    'settings.voiceGuidanceDetail': 'Habla correcciones de posicionamiento durante la captura en',
    'tabs.devices': 'Dispositivos',
    'tabs.home': 'Inicio',
    'tabs.learn': 'Aprender',
    'tabs.wallet': 'Billetera',
    'tabs.work': 'Trabajo',
    'task.due': 'Vence',
    'task.min': 'min',
    'task.open': 'Abrir',
    'task.progress': 'Progreso',
    'task.remote': 'Remoto',
    'uploads.failed': 'Fallidas',
    'uploads.queueClear': 'La cola está limpia',
    'uploads.queueClearDetail': 'Los archivos capturados se guardan localmente y aparecen aquí antes de sincronizarse con Cosaarthi.',
    'uploads.queued': 'En cola',
    'uploads.title': 'Cargas',
    'uploads.uploadQueue': 'Cola de cargas',
    'uploads.uploading': 'Cargando',
    'wallet.amount': 'Monto',
    'wallet.availableBalance': 'Saldo disponible',
    'wallet.earnings': 'Ganancias',
    'wallet.earningsByJobType': 'Ganancias por tipo de trabajo',
    'wallet.ledger': 'Libro',
    'wallet.lifetime': 'Vida total',
    'wallet.pending': 'Pendiente',
    'wallet.requestWithdrawal': 'Solicitar retiro',
    'wallet.thisWeek': 'Esta semana',
    'wallet.title': 'Billetera',
    'wallet.withdraw': 'Retirar',
    'wallet.withdrawalActivity': 'Actividad de retiros',
    'work.annotate': 'Anotar',
    'work.annotationTitle': 'Trabajo de anotación',
    'work.blockedBy': 'Captura bloqueada por',
    'work.capture': 'Captura',
    'work.captureTitle': 'Trabajo de captura',
    'work.modeTitle': 'Modos de trabajo Cosaarthi',
    'work.noTasks': 'Sin tareas',
    'work.rate': 'Calificar',
    'work.rateTitle': 'Trabajo de calificación',
    'work.survey': 'Encuesta',
    'work.surveyTitle': 'Trabajo de encuesta',
    'work.transcribe': 'Transcribir',
    'work.transcriptionTitle': 'Trabajo de transcripción',
  },
  hi: {
    'app.settings': 'ऐप सेटिंग्स',
    'camera.allowCamera': 'कैमरा अनुमति दें',
    'camera.allowRecording': 'रिकॉर्डिंग अनुमति दें',
    'camera.cameraPermission': 'कैमरा अनुमति',
    'camera.cameraPermissionDetail': 'कार्य प्रमाण कैप्चर करने के लिए कैमरा एक्सेस चाहिए।',
    'camera.capture': 'कैप्चर',
    'camera.captureImage': 'इमेज कैप्चर करें',
    'camera.captureVideo': 'वीडियो कैप्चर करें',
    'camera.imageCapture': 'इमेज कैप्चर',
    'camera.pickImage': 'इमेज चुनें',
    'camera.pickVideo': 'वीडियो चुनें',
    'camera.recordVideo': 'वीडियो रिकॉर्ड करें',
    'camera.recordingPermission': 'कैमरा और माइक्रोफ़ोन अनुमति',
    'camera.recordingPermissionDetail': 'कार्य प्रमाण रिकॉर्ड करने के लिए कैमरा और माइक्रोफ़ोन चाहिए।',
    'camera.stopRecording': 'रिकॉर्डिंग रोकें',
    'camera.videoCapture': 'वीडियो कैप्चर',
    'common.automatic': 'स्वचालित',
    'common.back': 'वापस',
    'common.cancel': 'रद्द करें',
    'common.mock': 'मॉक',
    'common.notConfigured': 'कॉन्फ़िगर नहीं',
    'common.off': 'बंद',
    'common.on': 'चालू',
    'common.open': 'खोलें',
    'common.optional': 'वैकल्पिक',
    'common.ready': 'तैयार',
    'common.required': 'आवश्यक',
    'common.saveAndContinue': 'सेव करें और जारी रखें',
    'common.savePreference': 'पसंद सेव करें',
    'common.selectingSaves': 'विकल्प चुनते ही सेव हो जाता है।',
    'devices.accepted': 'स्वीकार किया गया',
    'devices.assignedDevices': 'असाइन किए गए डिवाइस',
    'devices.awaitingCustody': 'कस्टडी स्वीकृति प्रतीक्षित',
    'devices.connection': 'कनेक्शन',
    'devices.firmware': 'फ़र्मवेयर',
    'devices.kitCustody': 'किट कस्टडी',
    'devices.offset': 'ऑफ़सेट',
    'devices.pairDevice': 'डिवाइस पेयर करें',
    'devices.sync': 'सिंक',
    'devices.syncStatus': 'सिंक स्थिति',
    'guidance.label.hold_steady': 'स्थिर रखें',
    'guidance.label.improve_light': 'रोशनी सुधारें',
    'guidance.label.move_closer': 'करीब जाएँ',
    'guidance.label.move_down': 'कैमरा नीचे करें',
    'guidance.label.move_farther': 'दूर जाएँ',
    'guidance.label.move_left': 'बाईं ओर जाएँ',
    'guidance.label.move_right': 'दाईं ओर जाएँ',
    'guidance.label.move_up': 'कैमरा ऊपर करें',
    'guidance.label.ready': 'तैयार',
    'guidance.label.straighten': 'सीधा करें',
    'guidance.label.wait_for_focus': 'फोकस की प्रतीक्षा करें',
    'home.clips': 'क्लिप',
    'home.edgePipeline': 'एज पाइपलाइन',
    'home.greeting': 'नमस्ते',
    'home.jobQueue': 'जॉब कतार',
    'home.labels': 'लेबल',
    'home.queue': 'कतार',
    'home.today': 'आज',
    'home.units': 'यूनिट',
    'languageRegion.changeLanguage': 'भाषा बदलें',
    'languageRegion.changeRegion': 'क्षेत्र बदलें',
    'languageRegion.chooseLanguage': 'अपनी भाषा चुनें',
    'languageRegion.chooseRegion': 'अपना क्षेत्र चुनें',
    'languageRegion.firstLoginSetup': 'पहली लॉगिन सेटअप',
    'languageRegion.language': 'भाषा',
    'languageRegion.region': 'क्षेत्र',
    'languageRegion.searchLanguages': 'भाषाएँ खोजें',
    'languageRegion.searchRegions': 'देश और क्षेत्र खोजें',
    'languageRegion.title': 'भाषा और क्षेत्र',
    'languageRegion.voiceAutomatic': 'सबसे अच्छी उपलब्ध TTS आवाज़',
    'learn.certifications': 'प्रमाणपत्र',
    'learn.complete': 'पूरा',
    'learn.expires': 'समाप्ति',
    'learn.title': 'प्रशिक्षण और प्रमाणपत्र',
    'learn.trainingModules': 'प्रशिक्षण मॉड्यूल',
    'login.choosePersona': 'पर्सोना चुनें',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.persona': 'पर्सोना',
    'login.signIn': 'साइन इन',
    'login.signInToContinue': 'जारी रखने के लिए साइन इन करें',
    'login.welcome': 'Cosaarthi में आपका स्वागत है',
    'profile.account': 'खाता',
    'profile.accountStatus': 'खाता स्थिति',
    'profile.active': 'सक्रिय',
    'profile.activeRole': 'सक्रिय भूमिका',
    'profile.assignedKit': 'असाइन की गई किट',
    'profile.certificationStatus': 'प्रमाणन स्थिति',
    'profile.certified': 'प्रमाणित',
    'profile.email': 'ईमेल',
    'profile.help': 'सहायता और समर्थन',
    'profile.logout': 'लॉग आउट',
    'profile.logoutAction': 'लॉग आउट',
    'profile.logoutMessage': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'profile.logoutTitle': 'लॉग आउट करें?',
    'profile.organization': 'संगठन',
    'profile.phone': 'फ़ोन',
    'profile.preferences': 'पसंदें',
    'profile.profile': 'प्रोफ़ाइल',
    'profile.support': 'समर्थन',
    'profile.userId': 'यूज़र ID',
    'profile.voiceGuidance': 'आवाज़ मार्गदर्शन',
    'qc.blocked': 'अवरुद्ध',
    'qc.confidence': 'विश्वास',
    'qc.indicators': 'Cosaarthi QC संकेतक',
    'readiness.blocked': 'अवरुद्ध',
    'readiness.gate': 'तैयारी गेट',
    'readiness.ready': 'तैयार',
    'role.actions': 'कार्रवाइयाँ',
    'role.demoShell': 'डेमो शेल',
    'role.mockedOnly': 'केवल मॉक',
    'role.navigation': 'नेविगेशन',
    'role.roleScope': 'भूमिका सीमा',
    'role.roleSwitcher': 'भूमिका स्विचर',
    'role.runDemoAction': 'डेमो कार्रवाई चलाएँ',
    'role.switchAccount': 'खाता बदलें',
    'role.worklist': 'कार्य सूची',
    'settings.languageRegion': 'भाषा और क्षेत्र',
    'settings.languageRegionDetail': 'ऐप भाषा, क्षेत्र और आवाज़ मार्गदर्शन बदलें।',
    'settings.voiceGuidance': 'आवाज़ मार्गदर्शन',
    'tabs.devices': 'डिवाइस',
    'tabs.home': 'होम',
    'tabs.learn': 'सीखें',
    'tabs.wallet': 'वॉलेट',
    'tabs.work': 'काम',
    'task.due': 'देय',
    'task.open': 'खोलें',
    'task.progress': 'प्रगति',
    'uploads.failed': 'असफल',
    'uploads.queued': 'कतार में',
    'uploads.title': 'अपलोड',
    'uploads.uploading': 'अपलोड हो रहा',
    'wallet.amount': 'राशि',
    'wallet.availableBalance': 'उपलब्ध बैलेंस',
    'wallet.ledger': 'लेजर',
    'wallet.pending': 'लंबित',
    'wallet.requestWithdrawal': 'निकासी अनुरोध',
    'wallet.title': 'वॉलेट',
    'wallet.withdraw': 'निकासी',
    'work.capture': 'कैप्चर',
    'work.modeTitle': 'Cosaarthi कार्य मोड',
    'work.noTasks': 'कोई कार्य नहीं',
    'work.rate': 'रेट करें',
    'work.survey': 'सर्वे',
    'work.transcribe': 'ट्रांसक्राइब',
  },
  te: {
    'app.settings': 'యాప్ సెట్టింగులు',
    'camera.allowCamera': 'కెమెరాను అనుమతించండి',
    'camera.allowRecording': 'రికార్డింగ్‌ను అనుమతించండి',
    'camera.cameraPermission': 'కెమెరా అనుమతి',
    'camera.cameraPermissionDetail': 'టాస్క్ ఆధారాన్ని క్యాప్చర్ చేయడానికి కెమెరా యాక్సెస్ అవసరం.',
    'camera.capture': 'క్యాప్చర్',
    'camera.audioCapture': 'ఆడియో క్యాప్చర్',
    'camera.captureAudio': 'ఆడియో క్యాప్చర్ చేయండి',
    'camera.captureChooser': 'క్యాప్చర్ ఎంపికను తెరవండి',
    'camera.captureDisabledBy': 'క్యాప్చర్ నిలిపివేసింది',
    'camera.captureImage': 'చిత్రం క్యాప్చర్ చేయండి',
    'camera.captureRequiredMedia': 'అవసరమైన మీడియాను క్యాప్చర్ చేయండి',
    'camera.captureVideo': 'వీడియో క్యాప్చర్ చేయండి',
    'camera.imageCapture': 'చిత్ర క్యాప్చర్',
    'camera.pickImage': 'చిత్రం ఎంచుకోండి',
    'camera.pickVideo': 'వీడియో ఎంచుకోండి',
    'camera.recording': 'రికార్డ్ అవుతోంది',
    'camera.recordVideo': 'వీడియో రికార్డ్ చేయండి',
    'camera.recordingPermission': 'కెమెరా మరియు మైక్రోఫోన్ అనుమతి',
    'camera.recordingPermissionDetail': 'టాస్క్ ఆధారాన్ని రికార్డ్ చేయడానికి కెమెరా మరియు మైక్రోఫోన్ అవసరం.',
    'camera.secondsCaptured': 'సెకన్లు క్యాప్చర్ అయ్యాయి',
    'camera.startRecording': 'రికార్డింగ్ ప్రారంభించండి',
    'camera.startTask': 'పని ప్రారంభించండి',
    'camera.startTaskDetail': 'మీడియాను క్యాప్చర్ చేసి, సమీక్షించి, ఆఫ్‌లైన్-సురక్షిత అప్‌లోడ్ క్యూ ద్వారా సమర్పించండి.',
    'camera.stopAndSave': 'ఆపి సేవ్ చేయండి',
    'camera.stopRecording': 'రికార్డింగ్ ఆపండి',
    'camera.taskMedia': 'పని మీడియా',
    'camera.videoCapture': 'వీడియో క్యాప్చర్',
    'common.automatic': 'స్వయంచాలకం',
    'common.back': 'వెనుకకు',
    'common.cancel': 'రద్దు',
    'common.changeLanguage': 'భాష మార్చండి',
    'common.close': 'మూసివేయండి',
    'common.continue': 'కొనసాగించండి',
    'common.mock': 'మాక్',
    'common.new': 'కొత్తది',
    'common.notConfigured': 'కాన్ఫిగర్ చేయలేదు',
    'common.off': 'ఆఫ్',
    'common.on': 'ఆన్',
    'common.open': 'తెరవండి',
    'common.optional': 'ఐచ్ఛికం',
    'common.pause': 'పాజ్',
    'common.play': 'ప్లే',
    'common.ready': 'సిద్ధం',
    'common.required': 'అవసరం',
    'common.retry': 'మళ్లీ ప్రయత్నించండి',
    'common.saveAndContinue': 'సేవ్ చేసి కొనసాగండి',
    'common.savePreference': 'ప్రాధాన్యాన్ని సేవ్ చేయండి',
    'common.selectingSaves': 'ఒక ఎంపికను ఎంచుకుంటే వెంటనే సేవ్ అవుతుంది.',
    'common.start': 'ప్రారంభించండి',
    'common.upload': 'అప్‌లోడ్',
    'contentValidation.checking': 'వీడియోను తనిఖీ చేస్తోంది...',
    'contentValidation.continueAnyway': 'అయినా కొనసాగించండి',
    'contentValidation.match': 'వీడియో పనికి సరిపోతుంది',
    'contentValidation.mismatch': 'వీడియో పనికి సరిపోలడం లేదు',
    'contentValidation.mocked': 'మాక్ ప్రాథమిక సెమాంటిక్ తనిఖీ',
    'contentValidation.retryRecording': 'రికార్డింగ్ మళ్లీ చేయండి',
    'contentValidation.uncertain': 'నమ్మకంగా ధృవీకరించలేకపోయాం',
    'appeals.appeals': 'అపీళ్లు',
    'appeals.createAppeal': 'అపీల్ సృష్టించండి',
    'appeals.createAppealDetail': 'submission.appeal ఉపయోగిస్తుంది. నిర్ణయాలు బ్యాకెండ్‌లో జరుగుతాయి.',
    'appeals.ground': 'కారణం',
    'appeals.recentAppeals': 'ఇటీవలి అపీళ్లు',
    'appeals.submissionAppeals': 'సమర్పణ అపీళ్లు',
    'appeals.submissionId': 'సమర్పణ ID',
    'appeals.submitAppeal': 'అపీల్ సమర్పించండి',
    'annotation.annotate': 'అనోటేట్',
    'annotation.confirmedLabel': 'నిర్ధారించిన లేబుల్',
    'annotation.edgeAutoLabel': 'ఎడ్జ్ ఆటో-లేబుల్ సిమ్యులేట్ చేయబడింది',
    'annotation.localValidation': 'స్థానిక ధృవీకరణ',
    'annotation.mobileAnnotation': 'మొబైల్ అనోటేషన్',
    'annotation.notes': 'నోట్స్',
    'annotation.preLabelDetail':
      'మొబైల్‌లో ప్రీ-లేబుల్ బాక్సులు సవరించవచ్చు. అధునాతన పాలిగాన్‌లు, కీపాయింట్లు మరియు సెగ్మెంటేషన్ Crowd Visual IDEలో ఉంటాయి.',
    'annotation.submitAnnotation': 'అనోటేషన్ సమర్పించండి',
    'devices.accepted': 'అంగీకరించబడింది',
    'devices.assignedDevices': 'కేటాయించిన పరికరాలు',
    'devices.awaitingCustody': 'కస్టడీ అంగీకారం కోసం వేచి ఉంది',
    'devices.connection': 'కనెక్షన్',
    'devices.firmware': 'ఫర్మ్‌వేర్',
    'devices.kitCustody': 'కిట్ కస్టడీ',
    'devices.offset': 'ఆఫ్‌సెట్',
    'devices.pairDevice': 'పరికరాన్ని జత చేయండి',
    'devices.sync': 'సింక్',
    'devices.syncStatus': 'సింక్ స్థితి',
    'devices.custodyDetail': 'బ్యాకెండ్ కస్టడీ చరిత్రే అధికారికం.',
    'guidance.label.hold_steady': 'స్థిరంగా పట్టుకోండి',
    'guidance.label.improve_light': 'వెలుతురును మెరుగుపరచండి',
    'guidance.label.move_closer': 'దగ్గరగా వెళ్లండి',
    'guidance.label.move_down': 'కెమెరాను క్రిందికి దించండి',
    'guidance.label.move_farther': 'దూరంగా వెళ్లండి',
    'guidance.label.move_left': 'ఎడమవైపు కదలండి',
    'guidance.label.move_right': 'కుడివైపు కదలండి',
    'guidance.label.move_up': 'కెమెరాను పైకి ఎత్తండి',
    'guidance.label.ready': 'సిద్ధం',
    'guidance.label.straighten': 'నేరుగా చేయండి',
    'guidance.label.wait_for_focus': 'ఫోకస్ కోసం వేచి ఉండండి',
    'home.clips': 'క్లిప్‌లు',
    'home.copilotDetail': 'స్థానిక మార్గదర్శక షెల్. తర్వాత ఏమిటి, సిద్ధత ఎందుకు ఆగింది లేదా QC ఎందుకు తిరస్కరించింది అని అడగండి.',
    'home.copilotTitle': 'ఎడ్జ్ కోపైలట్',
    'home.earningsLedger': 'వర్కర్ లెడ్జర్ నుండి ఆదాయం',
    'home.edgePipeline': 'ఎడ్జ్ పైప్‌లైన్',
    'home.edgePipelineDetail': 'నిజమైన ప్రొవైడర్ కాన్ఫిగర్ చేయకపోతే ఎడ్జ్ AI ఇంటిగ్రేషన్లు సిమ్యులేట్ చేయబడతాయి.',
    'home.greeting': 'నమస్కారం',
    'home.jobQueue': 'పని క్యూలు',
    'home.jobQueueDetail': 'వర్కర్ API నుండి అందుబాటులో/ప్రస్తుత పనులు.',
    'home.labels': 'లేబుల్‌లు',
    'home.mockApi': 'మాక్ API',
    'home.qcExplanation': 'QC వివరణ',
    'home.queue': 'క్యూ',
    'home.readinessBlocker': 'సిద్ధత అడ్డంకి',
    'home.today': 'ఈరోజు',
    'home.units': 'యూనిట్‌లు',
    'home.whatsNext': 'తర్వాత ఏమిటి?',
    'languageRegion.accountScope': 'ఈ ప్రాధాన్యాలు మీ ఖాతాతో అన్ని పాత్రలలో కొనసాగుతాయి.',
    'languageRegion.changeLanguage': 'భాష మార్చండి',
    'languageRegion.changeRegion': 'ప్రాంతం మార్చండి',
    'languageRegion.chooseLanguage': 'మీ భాషను ఎంచుకోండి',
    'languageRegion.chooseRegion': 'మీ ప్రాంతాన్ని ఎంచుకోండి',
    'languageRegion.chooseAppLanguage': 'యాప్ భాషను ఎంచుకోండి',
    'languageRegion.chooseWorkingRegion': 'పని చేసే దేశం లేదా ప్రాంతాన్ని ఎంచుకోండి',
    'languageRegion.emptyLanguages': 'భాషలు కనబడలేదు.',
    'languageRegion.emptyRegions': 'ప్రాంతాలు కనబడలేదు.',
    'languageRegion.explicitChoice': 'మీరు ఇంకా స్పష్టంగా ఎంచుకుని సేవ్ చేయాలి.',
    'languageRegion.firstLoginSetup': 'మొదటి లాగిన్ సెటప్',
    'languageRegion.language': 'భాష',
    'languageRegion.languageRequired': 'భాష అవసరం',
    'languageRegion.region': 'ప్రాంతం',
    'languageRegion.regionRequired': 'ప్రాంతం అవసరం',
    'languageRegion.searchLanguages': 'భాషలను వెతకండి',
    'languageRegion.searchRegions': 'దేశాలు మరియు ప్రాంతాలను వెతకండి',
    'languageRegion.selectLanguageDetail': 'Cosaarthiలో ఉపయోగించాలనుకునే భాషను ఎంచుకోండి.',
    'languageRegion.selectRegionDetail': 'మీ పని చేసే దేశం లేదా ప్రాంతాన్ని ఎంచుకోండి. దాన్ని GPS నుండి ఊహించము.',
    'languageRegion.suggestedFromDevice': 'పరికరం నుండి సూచన',
    'languageRegion.title': 'భాష మరియు ప్రాంతం',
    'languageRegion.voiceAutomatic': 'అందుబాటులో ఉన్న ఉత్తమ TTS స్వరం స్వయంచాలకంగా',
    'languageRegion.voiceLocaleDetail': 'కెమెరా స్థాన మార్గదర్శకాలు ఉపయోగించేది',
    'learn.certificationDetail': 'సర్టిఫికేషన్ స్థితి సిద్ధత గేట్‌లో భాగం.',
    'learn.certifications': 'సర్టిఫికేషన్లు',
    'learn.complete': 'పూర్తి',
    'learn.continueTraining': 'కొనసాగించండి',
    'learn.expires': 'గడువు',
    'learn.startTraining': 'ప్రారంభించండి',
    'learn.title': 'శిక్షణ మరియు సర్టిఫికేషన్లు',
    'learn.trainingDetail': 'అవసరమైన అభ్యాసం క్యాప్చర్ సిద్ధతను నియంత్రిస్తుంది.',
    'learn.trainingModules': 'శిక్షణ మాడ్యూల్స్',
    'login.assignedByBackend': 'సైన్ ఇన్ తర్వాత బ్యాకెండ్ కేటాయిస్తుంది',
    'login.choosePersona': 'పర్సోనాను ఎంచుకోండి',
    'login.demoPassword': 'డెమో పాస్‌వర్డ్',
    'login.demoRolePicker': 'డెమో-మాత్రమే పాత్ర ఎంపిక',
    'login.email': 'ఇమెయిల్',
    'login.mockApiLogin': 'మాక్ API లాగిన్',
    'login.password': 'పాస్‌వర్డ్',
    'login.persona': 'పర్సోనా',
    'login.personaSelector': 'పర్సోనా ఎంపిక',
    'login.signIn': 'సైన్ ఇన్',
    'login.signInToContinue': 'కొనసాగడానికి సైన్ ఇన్ చేయండి',
    'login.welcome': 'Cosaarthiకి స్వాగతం',
    'profile.about': 'గురించి',
    'profile.aboutDetail': 'Cosaarthi Mobile డెమో షెల్',
    'profile.account': 'ఖాతా',
    'profile.accountStatus': 'ఖాతా స్థితి',
    'profile.active': 'సక్రియం',
    'profile.activeRole': 'సక్రియ పాత్ర',
    'profile.assignedKit': 'కేటాయించిన కిట్',
    'profile.certificationStatus': 'సర్టిఫికేషన్ స్థితి',
    'profile.certified': 'సర్టిఫైడ్',
    'profile.chooseLanguageRegion': 'భాష మరియు ప్రాంతాన్ని ఎంచుకోండి',
    'profile.email': 'ఇమెయిల్',
    'profile.entityId': 'ఎంటిటీ ID',
    'profile.entityType': 'ఎంటిటీ రకం',
    'profile.expired': 'గడువు ముగిసింది',
    'profile.help': 'సహాయం మరియు మద్దతు',
    'profile.helpDetail': 'ఉత్పత్తిలో మద్దతు చానెల్లు బ్యాకెండ్‌కు కనెక్ట్ అవుతాయి.',
    'profile.logout': 'లాగ్ అవుట్',
    'profile.logoutAction': 'లాగ్ అవుట్',
    'profile.logoutMessage': 'మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
    'profile.logoutTitle': 'లాగ్ అవుట్?',
    'profile.organization': 'సంస్థ',
    'profile.phone': 'ఫోన్',
    'profile.preferences': 'ప్రాధాన్యాలు',
    'profile.profile': 'ప్రొఫైల్',
    'profile.roleScope': 'పాత్ర పరిధి',
    'profile.settingsDetail': 'యాప్, సెషన్, ఆఫ్‌లైన్ క్యూ మరియు స్థానికీకరణ నియంత్రణలు',
    'profile.status': 'స్థితి',
    'profile.support': 'మద్దతు',
    'profile.tenant': 'టెనెంట్',
    'profile.tenantId': 'టెనెంట్ ID',
    'profile.userId': 'వినియోగదారు ID',
    'profile.voiceGuidance': 'వాయిస్ మార్గదర్శకం',
    'profile.workerId': 'వర్కర్ ID',
    'qc.blocked': 'అడ్డుకుంది',
    'qc.confidence': 'నమ్మకం',
    'qc.detail': 'స్థానిక స్థాన తనిఖీలు క్యాప్చర్‌కు మార్గనిర్దేశం చేస్తాయి; తుది QC బ్యాకెండ్ నుండి వస్తుంది.',
    'qc.indicators': 'Cosaarthi QC సూచికలు',
    'qc.localFallback': 'స్థానిక స్థాన ఫాల్‌బ్యాక్',
    'readiness.blocked': 'అడ్డుకుంది',
    'readiness.detail': 'తప్పనిసరి Cosaarthi అవసరం విఫలమైతే క్యాప్చర్ నిలిపివేయబడుతుంది.',
    'readiness.gate': 'సిద్ధత గేట్',
    'readiness.ready': 'సిద్ధం',
    'role.actions': 'చర్యలు',
    'role.actionsDetail': 'సక్రియ నియంత్రణలు షేర్డ్ ఇన్-మెమరీ డెమో స్థితిని మార్చుతాయి. బ్యాకెండ్-మాత్రమే నియంత్రణలు నిలిపివేయబడతాయి.',
    'role.backendUnavailable': 'బ్యాకెండ్ అందుబాటులో లేదు',
    'role.copilot': 'కోపైలట్',
    'role.copilotDetail': 'సూచన కోసం మాత్రమే చూపే రిఫరెన్స్ వర్క్‌ఫ్లో పాత్ర-సంబంధిత సూచనలు.',
    'role.demoShell': 'డెమో షెల్',
    'role.demoState': 'డెమో స్థితి',
    'role.demoUser': 'డెమో వినియోగదారు',
    'role.hiddenByRbac': 'RBAC ద్వారా దాచబడింది',
    'role.mockedOnly': 'మాక్ మాత్రమే',
    'role.navigation': 'నావిగేషన్',
    'role.navigationDetail': 'Cosaarthi ప్రోటోటైప్ నుండి రిఫరెన్స్ నావిగేషన్. బ్యాకెండ్ స్క్రీన్‌లు లేని చోట మొబైల్ షెల్‌లను మాత్రమే తెరుస్తుంది.',
    'role.notSignedIn': 'సైన్ ఇన్ కాలేదు',
    'role.roleScope': 'పాత్ర పరిధి',
    'role.roleScopeDetail': 'కనిపించే సామర్థ్యాలు పాత్ర అనుమతులు మరియు ప్రస్తుత Cosaarthi పాత్ర పరిధి ద్వారా ఫిల్టర్ అవుతాయి.',
    'role.roleSwitcher': 'పాత్ర మార్పిడి',
    'role.runDemoAction': 'డెమో చర్యను అమలు చేయండి',
    'role.session': 'సెషన్',
    'role.switchAccount': 'ఖాతా మార్చండి',
    'role.switcherDetail': 'అదే డెమో ఖాతా, భద్రపరచిన SecureStore సెషన్.',
    'role.worklist': 'పని జాబితా',
    'settings.backendMode': 'బ్యాకెండ్ మోడ్',
    'settings.languageRegion': 'భాష మరియు ప్రాంతం',
    'settings.languageRegionDetail': 'యాప్ భాష, ప్రాంతం మరియు వాయిస్ మార్గదర్శకాన్ని మార్చండి.',
    'settings.largeTouchTargets': 'పెద్ద టచ్ లక్ష్యాలు',
    'settings.largeTouchTargetsDetail': 'నియంత్రణలు కనీసం 48px ఎత్తులో ఉంటాయి.',
    'settings.mockApiAdapter': 'మాక్ API అడాప్టర్',
    'settings.notConfigured': 'కాన్ఫిగర్ చేయలేదు',
    'settings.offlineQueue': 'ఆఫ్‌లైన్ క్యూ',
    'settings.offlineQueueDetail': 'అప్‌లోడ్ మెటాడేటా Expo SQLiteలో నిల్వ అవుతుంది.',
    'settings.sessionStorage': 'సెషన్ నిల్వ',
    'settings.sessionStorageDetail': 'యాక్సెస్ మరియు రిఫ్రెష్ టోకెన్లు Expo SecureStoreలో నిల్వ చేయబడతాయి.',
    'settings.voiceAutomatic': 'TTS స్వరం: లోకేల్‌కు అందుబాటులో ఉన్న ఉత్తమ స్వరం స్వయంచాలకంగా.',
    'settings.voiceGuidance': 'వాయిస్ మార్గదర్శకం',
    'settings.voiceGuidanceDetail': 'కెమెరా క్యాప్చర్ సమయంలో స్థాన సవరణలను మాట్లాడండి',
    'tabs.devices': 'పరికరాలు',
    'tabs.home': 'హోమ్',
    'tabs.learn': 'నేర్చుకోండి',
    'tabs.wallet': 'వాలెట్',
    'tabs.work': 'పని',
    'notifications.allClear': 'అన్నీ క్లియర్',
    'notifications.markAllRead': 'అన్నీ చదివినట్లుగా గుర్తించండి',
    'notifications.markRead': 'చదివినట్లుగా గుర్తించండి',
    'notifications.noAlerts': 'ప్రస్తుతం హెచ్చరికలు లేవు.',
    'notifications.notifications': 'నోటిఫికేషన్లు',
    'notifications.workerAlerts': 'వర్కర్ హెచ్చరికలు',
    'rating.accuracy': 'ఖచ్చితత్వం',
    'rating.helpfulness': 'ఉపయోగకరత',
    'rating.justification': 'వివరణ',
    'rating.optionA': 'ఎంపిక A',
    'rating.optionAText': 'ఉత్పత్తి కుటుంబాన్ని వర్గీకరించడానికి కనిపించే షెల్ఫ్ లేబుల్ మరియు ఐల్ సందర్భాన్ని ఉపయోగించండి.',
    'rating.optionB': 'ఎంపిక B',
    'rating.optionBText': 'దగ్గరలోని లోగో ఆధారంగా ఉత్పత్తిని ఊహించి మిగతావాటిని అనిశ్చితంగా గుర్తించండి.',
    'rating.preference': 'ప్రాధాన్యం',
    'rating.rate': 'రేట్',
    'rating.rubric': 'రూబ్రిక్',
    'rating.safety': 'భద్రత',
    'rating.sideBySideRating': 'పక్కపక్కన రేటింగ్',
    'rating.submitRating': 'రేటింగ్ సమర్పించండి',
    'rating.tie': 'సమం',
    'survey.assetId': 'ఆస్తి ID',
    'survey.autoQcPhotoAttached': 'ఆటో-QC ఫోటో జతచేయబడింది',
    'survey.autoQcPhotoPending': 'ఆటో-QC ఫోటో పెండింగ్‌లో ఉంది',
    'survey.condition': 'స్థితి',
    'survey.condition.damaged': 'దెబ్బతిన్నది',
    'survey.condition.good': 'మంచిది',
    'survey.condition.missing': 'లేనిది',
    'survey.condition.unsafe': 'సురక్షితం కాదు',
    'survey.conditionSurvey': 'స్థితి సర్వే',
    'survey.observation': 'పరిశీలన',
    'survey.photo': 'ఫోటో',
    'survey.qrRackDetail': 'V1 టైప్ చేసిన గుర్తింపులను మద్దతు ఇస్తుంది; ప్రొడక్షన్ డివైస్ సర్వీస్ ప్రారంభమైనప్పుడు బార్‌కోడ్ స్కానింగ్‌ను జోడించవచ్చు.',
    'survey.qrRackIdentifier': 'QR / ర్యాక్ గుర్తింపు',
    'survey.submitSurvey': 'సర్వే సమర్పించండి',
    'survey.survey': 'సర్వే',
    'task.due': 'గడువు',
    'task.checklist': 'చెక్‌లిస్ట్',
    'task.fallbackTitle': 'పని',
    'task.min': 'నిమి',
    'task.open': 'తెరవండి',
    'task.openWorkflow': 'వర్క్‌ఫ్లో తెరవండి',
    'task.progress': 'ప్రగతి',
    'task.qualityBar': 'నాణ్యత ప్రమాణం',
    'task.remote': 'రిమోట్',
    'task.requires': 'అవసరం',
    'task.startCapture': 'క్యాప్చర్ ప్రారంభించండి',
    'task.taskPayout': 'పని చెల్లింపు',
    'transcription.audioSegment': 'ఆడియో భాగం 00:00-00:15',
    'transcription.audioTranscription': 'ఆడియో ట్రాన్స్‌క్రిప్షన్',
    'transcription.edgePreTranscription': 'ఎడ్జ్ ప్రీ-ట్రాన్స్‌క్రిప్షన్ సిమ్యులేట్ చేయబడింది',
    'transcription.edgePreTranscriptionDetail': 'ఎడ్జ్ ప్రీ-ట్రాన్స్‌క్రిప్షన్ సిమ్యులేట్ చేయబడింది. బ్యాకెండ్ తిరిగి ఇచ్చే వరకు తుది WERను ఊహించవద్దు.',
    'transcription.segmentContext': 'సెగ్మెంట్ సందర్భం',
    'transcription.submitTranscription': 'ట్రాన్స్‌క్రిప్షన్ సమర్పించండి',
    'transcription.transcribe': 'ట్రాన్స్‌క్రైబ్',
    'transcription.transcript': 'ట్రాన్స్‌క్రిప్ట్',
    'uploads.appealResult': 'ఫలితంపై అపీల్ చేయండి',
    'uploads.attempt': 'ప్రయత్నం',
    'uploads.backendProcessing': 'బ్యాకెండ్ ఇంకా ఈ సమర్పణను ప్రాసెస్ చేస్తోంది.',
    'uploads.defaultProgressMessage': 'కేంద్రీకృత Cosaarthi API అడాప్టర్ ద్వారా అప్‌లోడ్ అవుతోంది.',
    'uploads.duplicateScore': 'డూప్లికేట్ స్కోర్',
    'uploads.failed': 'విఫలమైనవి',
    'uploads.itemNotFound': 'అప్‌లోడ్ అంశం కనబడలేదు.',
    'uploads.mediaPreview': 'మీడియా ప్రీవ్యూ',
    'uploads.notFound': 'అప్‌లోడ్ కనబడలేదు.',
    'uploads.queueClear': 'క్యూ ఖాళీగా ఉంది',
    'uploads.queueClearDetail': 'క్యాప్చర్ చేసిన ఫైళ్ళు స్థానికంగా నిల్వై Cosaarthi బ్యాకెండ్‌కు సింక్ అయ్యే ముందు ఇక్కడ కనిపిస్తాయి.',
    'uploads.queued': 'క్యూలో',
    'uploads.retryUpload': 'అప్‌లోడ్ మళ్లీ ప్రయత్నించండి',
    'uploads.submissionResult': 'సమర్పణ ఫలితం',
    'uploads.title': 'అప్‌లోడ్‌లు',
    'uploads.status.accepted': 'అంగీకరించబడింది',
    'uploads.status.completed': 'పూర్తైంది',
    'uploads.status.duplicate': 'డూప్లికేట్',
    'uploads.status.failed': 'విఫలమైంది',
    'uploads.status.pending': 'పెండింగ్',
    'uploads.status.possibleDuplicate': 'సాధ్యమైన డూప్లికేట్',
    'uploads.status.processing': 'ప్రాసెసింగ్',
    'uploads.status.queued': 'క్యూలో',
    'uploads.status.rejected': 'తిరస్కరించబడింది',
    'uploads.status.uploaded': 'అప్‌లోడ్ అయింది',
    'uploads.status.uploading': 'అప్‌లోడ్ అవుతోంది',
    'uploads.uploadProgress': 'అప్‌లోడ్ ప్రగతి',
    'uploads.uploadQueue': 'అప్‌లోడ్ క్యూ',
    'uploads.uploading': 'అప్‌లోడ్ అవుతోంది',
    'uploads.viewResult': 'ఫలితం చూడండి',
    'validation.addJustification': 'స్పష్టమైన వివరణను జోడించండి',
    'validation.addLabel': 'సమర్పించే ముందు లేబుల్ జోడించండి',
    'validation.addObservation': 'చిన్న పరిశీలనను జోడించండి',
    'validation.amountAboveLimit': 'మొత్తం V1 పరిమితిని మించింది',
    'validation.contextShort': 'సందర్భాన్ని చిన్నగా ఉంచండి',
    'validation.enterAssetId': 'ర్యాక్ లేదా ఆస్తి గుర్తింపును నమోదు చేయండి',
    'validation.enterSubmissionId': 'సమర్పణ IDను నమోదు చేయండి',
    'validation.explainAppeal': 'QA ఈ సమర్పణను ఎందుకు సమీక్షించాలో వివరించండి',
    'validation.minWithdrawal': 'కనీస విత్‌డ్రా 100',
    'validation.notesUnderLimit': 'నోట్స్‌ను 280 అక్షరాల లోపు ఉంచండి',
    'validation.passwordMin': 'పాస్‌వర్డ్ కనీసం 4 అక్షరాలు ఉండాలి',
    'validation.transcriptShort': 'ట్రాన్స్‌క్రిప్ట్ చాలా చిన్నది',
    'validation.validEmail': 'చెల్లుబాటు అయ్యే ఇమెయిల్ నమోదు చేయండి',
    'validation.wholeAmount': 'పూర్తి మొత్తాన్ని నమోదు చేయండి',
    'wallet.amount': 'మొత్తం',
    'wallet.availableBalance': 'లభ్యమైన బ్యాలెన్స్',
    'wallet.earnings': 'ఆదాయం',
    'wallet.earningsByJobType': 'పని రకం వారీగా ఆదాయం',
    'wallet.earningsByJobTypeDetail': 'బ్యాలెన్స్ సర్వర్ ఆదాయ లెడ్జర్ నుండి లెక్కించబడుతుంది.',
    'wallet.ledger': 'లెడ్జర్',
    'wallet.lifetime': 'జీవితకాలం',
    'wallet.pending': 'పెండింగ్',
    'wallet.requestWithdrawal': 'విత్‌డ్రా అభ్యర్థించండి',
    'wallet.thisWeek': 'ఈ వారం',
    'wallet.title': 'వాలెట్',
    'wallet.withdraw': 'విత్‌డ్రా',
    'wallet.withdrawDetail': 'wallet.withdraw ఉపయోగిస్తుంది మరియు సెటిల్‌మెంట్‌ను నకిలీ చేయదు.',
    'wallet.withdrawalActivity': 'విత్‌డ్రా కార్యాచరణ',
    'work.annotate': 'అనోటేట్',
    'work.annotationDetail': 'ఎడ్జ్ ఆటో-లేబుల్ ఇచ్చిన తేలికపాటి బాక్సులు మరియు లేబుళ్లను నిర్ధారించండి.',
    'work.annotationTitle': 'అనోటేషన్ పని',
    'work.blockedBy': 'క్యాప్చర్ అడ్డుకున్నది',
    'work.capture': 'క్యాప్చర్',
    'work.captureBlockedDetail': 'తప్పనిసరి సిద్ధత తనిఖీలు పాస్ అయితేనే క్యాప్చర్ తెరుస్తుంది.',
    'work.captureDetail': 'స్థానిక QC మార్గదర్శకంతో కెమెరా, చిత్రం, వీడియో మరియు ఆడియో సేకరణ.',
    'work.captureTitle': 'క్యాప్చర్ పని',
    'work.modeTitle': 'Cosaarthi పని మోడ్‌లు',
    'work.noTasks': 'పనులు లేవు',
    'work.noTasksDetail': 'టెనెంట్ QA మరిన్ని స్లాట్లు తెరిచినప్పుడు కొత్త Cosaarthi పని ఇక్కడ కనిపిస్తుంది.',
    'work.rate': 'రేట్',
    'work.rateDetail': 'ప్రాధాన్యం, రూబ్రిక్ మరియు వివరణతో పక్కపక్కన మోడల్ మూల్యాంకనం.',
    'work.rateTitle': 'రేటింగ్ పని',
    'work.submissionDetail': 'submission.create ఉపయోగిస్తుంది.',
    'work.survey': 'సర్వే',
    'work.surveyDetail': 'QR, ర్యాక్ లేదా ఆస్తి స్థితి సర్వేలను ఆటో-QC ఫోటో సందర్భంతో సమర్పించండి.',
    'work.surveyTitle': 'సర్వే పని',
    'work.transcribe': 'ట్రాన్స్‌క్రైబ్',
    'work.transcriptionDetail': 'ప్రోగ్రెస్ UIతో ఆడియోను సమీక్షించి సవరించగల ట్రాన్స్‌క్రిప్ట్‌లను సమర్పించండి.',
    'work.transcriptionTitle': 'ట్రాన్స్‌క్రిప్షన్ పని',
  },
  ur: {
    'app.settings': 'ایپ سیٹنگز',
    'common.back': 'واپس',
    'common.cancel': 'منسوخ کریں',
    'common.off': 'بند',
    'common.on': 'چالو',
    'common.open': 'کھولیں',
    'guidance.label.hold_steady': 'مستحکم رکھیں',
    'guidance.label.improve_light': 'روشنی بہتر کریں',
    'guidance.label.move_closer': 'قریب جائیں',
    'guidance.label.move_down': 'کیمرا نیچے کریں',
    'guidance.label.move_farther': 'دور جائیں',
    'guidance.label.move_left': 'بائیں جائیں',
    'guidance.label.move_right': 'دائیں جائیں',
    'guidance.label.move_up': 'کیمرا اوپر کریں',
    'guidance.label.ready': 'تیار',
    'guidance.label.straighten': 'سیدھا کریں',
    'guidance.label.wait_for_focus': 'فوکس کا انتظار کریں',
    'languageRegion.title': 'زبان اور علاقہ',
    'profile.logoutAction': 'لاگ آؤٹ',
    'profile.logoutMessage': 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
    'profile.logoutTitle': 'لاگ آؤٹ؟',
    'settings.languageRegion': 'زبان اور علاقہ',
    'settings.languageRegionDetail': 'ایپ کی زبان، علاقہ اور آواز کی رہنمائی تبدیل کریں۔',
    'settings.voiceGuidance': 'آواز رہنمائی',
    'tabs.devices': 'آلات',
    'tabs.home': 'ہوم',
    'tabs.learn': 'سیکھیں',
    'tabs.wallet': 'والیٹ',
    'tabs.work': 'کام',
  },
};

const guidanceStrings: Partial<Record<string, Partial<Record<PositionCorrection, string>>>> = {
  ar: {
    hold_steady: 'أمسك الهاتف بثبات.',
    improve_light: 'انتقل إلى مكان أكثر إضاءة.',
    move_closer: 'اقترب من الهدف.',
    move_down: 'اخفض الكاميرا قليلاً.',
    move_farther: 'ابتعد قليلاً.',
    move_left: 'حرّك الكاميرا قليلاً إلى اليسار.',
    move_right: 'حرّك الكاميرا قليلاً إلى اليمين.',
    move_up: 'ارفع الكاميرا قليلاً.',
    ready: 'الوضع جيد. يمكنك بدء التسجيل.',
    straighten: 'عدّل الهاتف قليلاً.',
    wait_for_focus: 'ابقَ ثابتاً حتى تركز الكاميرا.',
  },
  es: {
    hold_steady: 'Mantén el teléfono estable.',
    improve_light: 'Muévete a un lugar con más luz.',
    move_closer: 'Acércate al objetivo.',
    move_down: 'Baja la cámara un poco.',
    move_farther: 'Aléjate un poco.',
    move_left: 'Mueve la cámara un poco a la izquierda.',
    move_right: 'Mueve la cámara un poco a la derecha.',
    move_up: 'Sube la cámara un poco.',
    ready: 'La posición se ve bien. Puedes empezar a grabar.',
    straighten: 'Endereza un poco el teléfono.',
    wait_for_focus: 'Mantente quieto mientras enfoca la cámara.',
  },
  hi: {
    hold_steady: 'फोन को स्थिर रखें।',
    improve_light: 'थोड़ी अधिक रोशनी वाली जगह पर जाएँ।',
    move_closer: 'लक्ष्य के थोड़ा करीब जाएँ।',
    move_down: 'कैमरा थोड़ा नीचे करें।',
    move_farther: 'थोड़ा पीछे जाएँ।',
    move_left: 'कैमरा थोड़ा बाईं ओर ले जाएँ।',
    move_right: 'कैमरा थोड़ा दाईं ओर ले जाएँ।',
    move_up: 'कैमरा थोड़ा ऊपर करें।',
    ready: 'स्थिति अच्छी है। आप रिकॉर्डिंग शुरू कर सकते हैं।',
    straighten: 'फोन को थोड़ा सीधा करें।',
    wait_for_focus: 'कैमरा फोकस होने तक स्थिर रहें।',
  },
  te: {
    hold_steady: 'ఫోన్‌ను స్థిరంగా పట్టుకోండి.',
    improve_light: 'మరింత వెలుతురు ఉన్న చోటుకు వెళ్లండి.',
    move_closer: 'లక్ష్యానికి కొంచెం దగ్గరగా వెళ్లండి.',
    move_down: 'కెమెరాను కొంచెం క్రిందికి దించండి.',
    move_farther: 'కొంచెం వెనక్కి వెళ్లండి.',
    move_left: 'కెమెరాను కొంచెం ఎడమవైపు కదపండి.',
    move_right: 'కెమెరాను కొంచెం కుడివైపు కదపండి.',
    move_up: 'కెమెరాను కొంచెం పైకి ఎత్తండి.',
    ready: 'స్థానం బాగుంది. మీరు రికార్డింగ్ ప్రారంభించవచ్చు.',
    straighten: 'ఫోన్‌ను కొంచెం సరిచేయండి.',
    wait_for_focus: 'కెమెరా ఫోకస్ అయ్యే వరకు స్థిరంగా ఉండండి.',
  },
  ur: {
    hold_steady: 'فون کو مستحکم رکھیں۔',
    improve_light: 'زیادہ روشن جگہ پر جائیں۔',
    move_closer: 'ہدف کے قریب جائیں۔',
    move_down: 'کیمرا تھوڑا نیچے کریں۔',
    move_farther: 'تھوڑا پیچھے جائیں۔',
    move_left: 'کیمرا تھوڑا بائیں طرف کریں۔',
    move_right: 'کیمرا تھوڑا دائیں طرف کریں۔',
    move_up: 'کیمرا تھوڑا اوپر کریں۔',
    ready: 'پوزیشن اچھی ہے۔ آپ ریکارڈنگ شروع کر سکتے ہیں۔',
    straighten: 'فون کو تھوڑا سیدھا کریں۔',
    wait_for_focus: 'کیمرا فوکس ہونے تک مستحکم رہیں۔',
  },
};

const missingKeys = new Set<string>();

function normalizeLanguage(languageCode?: string) {
  return languageCode?.split('-')[0]?.toLowerCase();
}

function logMissingKey(key: string, languageCode?: string) {
  if (process.env.NODE_ENV === 'test' || process.env.NODE_ENV === 'production') {
    return;
  }
  const normalizedLanguage = normalizeLanguage(languageCode);
  if (!normalizedLanguage || normalizedLanguage === 'en') {
    return;
  }
  const logKey = `${normalizedLanguage}:${key}`;
  if (missingKeys.has(logKey)) {
    return;
  }
  missingKeys.add(logKey);
  console.warn(`[i18n] Missing ${normalizedLanguage} translation for "${key}"`);
}

export function translate(key: StringKey, languageCode?: string) {
  const normalizedLanguage = normalizeLanguage(languageCode);
  const translated = strings[normalizedLanguage ?? '']?.[key];
  if (!translated) {
    logMissingKey(key, normalizedLanguage);
  }
  return translated ?? englishStrings[key];
}

export function getLocalizedCorrectionInstruction(correction: PositionCorrection, languageCode?: string) {
  const normalizedLanguage = normalizeLanguage(languageCode);
  const translated = guidanceStrings[normalizedLanguage ?? '']?.[correction];
  if (!translated) {
    logMissingKey(`guidance.${correction}`, normalizedLanguage);
  }
  return translated ?? CORRECTION_INSTRUCTIONS[correction];
}

export function getLocalizedCorrectionLabel(correction: PositionCorrection, languageCode?: string) {
  return translate(`guidance.label.${correction}` as StringKey, languageCode);
}

export function getSupportedTranslationLocales() {
  return ['en', ...Object.keys(strings)];
}
