# =============================================================================
# SourceHub — the entire developer interface.
#
# Target names come from sourcehub-build-guide.html and should not be renamed:
# they are what the documentation tells a new engineer to type.
#
# Windows: use `pwsh ./make.ps1 <target>`, which wraps the same commands.
# =============================================================================

COMPOSE := docker compose -f infra/compose.yaml
BACKEND  := backend
FRONTEND := frontend

.DEFAULT_GOAL := help
.PHONY: help up down seed migrate-status revision verify-schema test lint format types logs ps psql reset install

help:  ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

# --- stack -------------------------------------------------------------------
up:  ## Start the stack and wait for health
	$(COMPOSE) up -d
	@echo "postgres  5432   ·  redis 6379  ·  minio 9000/9001  ·  mailpit 8025"

down:  ## Stop the stack, keep data
	$(COMPOSE) down

reset:  ## Wipe data and reapply db/*.sql from scratch
	$(COMPOSE) down -v
	$(COMPOSE) up -d
	@echo "database rebuilt from db/*.sql"

logs:  ## Tail a service: make logs s=postgres
	$(COMPOSE) logs -f $(s)

ps:  ## Show service status
	$(COMPOSE) ps

psql:  ## Open psql as the superuser
	$(COMPOSE) exec postgres psql -U postgres -d sourcehub

psql-app:  ## Open psql as sourcehub_app — RLS applies, so you see nothing without a context
	$(COMPOSE) exec -e PGPASSWORD=sourcehub_app_dev_password postgres \
		psql -U sourcehub_app -d sourcehub

# --- database ----------------------------------------------------------------
# db/*.sql is the bootstrap: it runs once, on an empty volume, and is how
# `make up` produces a working database with no application code. Alembic takes
# over for anything that must evolve a database already holding data.
# Demo data is NOT loaded here: db/910_seed_demo.sql is part of the bootstrap,
# so `make up` on an empty volume already has it.
seed:  ## Apply outstanding migrations to a database that already has data
	cd $(BACKEND) && alembic upgrade head

migrate-status:  ## Which revision is this database on?
	cd $(BACKEND) && alembic current

revision:  ## New migration: make revision rev=0003 m="what it does"
	cd $(BACKEND) && alembic revision --autogenerate --rev-id "$(rev)" -m "$(m)"
	@echo ""
	@echo "  RLS policies are NEVER autogenerated. If this revision touches a"
	@echo "  table with policies, hand-write them into the migration now."
	@echo "  Put the same change in db/*.sql too, then run: make verify-schema"

verify-schema:  ## Diff a fresh db/*.sql build against the running database
	sh infra/verify_schema.sh

# --- quality -----------------------------------------------------------------
lint:  ## ruff + mypy + import-linter + eslint
	cd $(BACKEND) && ruff check . && ruff format --check . && mypy && lint-imports
	cd $(FRONTEND) && npm run lint && npm run typecheck

format:  ## Auto-fix what can be auto-fixed
	cd $(BACKEND) && ruff check --fix . && ruff format .
	cd $(FRONTEND) && npx prettier --write src

test:  ## Full suite: unit, isolation, integration, web
	cd $(BACKEND) && pytest
	cd $(FRONTEND) && npm run test

test-isolation:  ## The cross-tenant checks. Never skipped.
	cd $(BACKEND) && pytest -m isolation -v

types:  ## Regenerate the TypeScript client from the live OpenAPI schema
	cd $(FRONTEND) && npm run types
	@echo "commit src/api/generated — CI fails if it drifts from the schema"

install:  ## Install both toolchains
	cd $(BACKEND) && pip install -e ".[dev]"
	cd $(FRONTEND) && npm install
