#!/bin/sh
# Concatenate db/*.sql into two files a managed database can be given directly.
#
# The compose entrypoint applies db/*.sql once, in filename order, on a fresh
# volume. A managed database — Azure, RDS, Cloud SQL — has no entrypoint, and
# pasting nineteen files into a query editor in the right order is exactly
# where a deployment goes wrong: 035_storage must precede 040_marketplace,
# 095_attachments must precede 100_rls, and a file applied out of turn fails
# in a way that reads like a different problem.
#
# Alembic is NOT the route for an empty database. Revision 0001 is a stamp-only
# baseline that creates nothing, so `alembic upgrade head` then tries to ALTER
# tables that do not exist. Alembic evolves a database that already has this
# schema; this script is how one gets it.
#
# Output is a build artifact of files already in the repository, so build/ is
# gitignored. A committed copy would be a second schema to keep in step, which
# is the drift infra/verify_schema.sh exists to catch.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT="$ROOT/build"
mkdir -p "$OUT"

# Structure, in the order the entrypoint would apply it. Listed explicitly
# rather than globbed: a new db/*.sql file should be a deliberate addition
# here, not something that silently joins a production bundle.
STRUCTURE="000_extensions 001_conventions 010_identity 020_rbac 030_onboarding
           035_storage 040_marketplace 050_delivery 060_qa 070_network
           080_ledger 090_notify_audit 095_attachments 100_rls
           110_auth_functions 120_workers_media 130_task_offers
           140_attachment_layout 150_downstream_documents 160_email_is_taken
           170_engagement 180_open_buyer 190_worker_skills"

# Required, and not demo data: without these there is no capability
# vocabulary, no role to grant, and nobody who can approve anything.
# 910_seed_demo is deliberately absent.
SEED="900_seed 905_seed_workers"

emit() {
  target=$1
  title=$2
  shift 2
  rev=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
  {
    echo "-- ============================================================================"
    echo "-- $title"
    echo "--"
    echo "-- GENERATED by infra/bundle_schema.sh from $rev. Do not edit: change the"
    echo "-- file under db/ and regenerate, or the two will drift."
    echo "--"
    echo "-- Apply to an EMPTY database, as one role. db/000 sets ALTER DEFAULT"
    echo "-- PRIVILEGES, which only covers tables created by that same role"
    echo "-- afterwards — switch users partway and later tables get no grants, so"
    echo "-- sourcehub_app silently cannot read them."
    echo "-- ============================================================================"
    echo
    for name in $@; do
      src="$ROOT/db/$name.sql"
      [ -f "$src" ] || { echo "missing: db/$name.sql" >&2; exit 1; }
      echo
      echo "-- >>> db/$name.sql >>>"
      echo
      cat "$src"
      echo
      echo "-- <<< db/$name.sql <<<"
      echo
    done
  } > "$target"
  printf '  %-22s %5s lines\n' "$(basename "$target")" "$(wc -l < "$target" | tr -d ' ')"
}

emit "$OUT/schema.sql" "SourceHub schema — structure only" $STRUCTURE
emit "$OUT/seed.sql"   "SourceHub seed — roles, permissions, first administrator" $SEED

echo
echo "Apply to the deployed database in this order:"
echo "  1. build/schema.sql"
echo "  2. build/seed.sql"
