"""${message}

Revisions in this project are sequential — 0001, 0002, 0003 — not hashes, so
generate one with:  alembic revision --rev-id 0003 -m "what it does"

READ THE AUTOGENERATED BODY BEFORE COMMITTING IT. Two known sources of noise:

  * Autogenerate compares Base.metadata, so it sees TABLES ONLY. Every RLS
    policy, SECURITY DEFINER function, trigger, partition and grant is
    invisible and must be hand-written here.
  * db/*.sql created its constraints with Postgres's default names, while the
    ORM declares db/base.py's NAMING_CONVENTION. Autogenerate reads that as
    hundreds of constraints to rename. Delete those unless renaming is the
    actual intent.

Whatever lands here belongs in db/*.sql too; `make verify-schema` diffs a fresh
bootstrap against the running database and fails if they disagree.

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
"""

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
