-- ============================================================================
-- 100 · Row-level security
--
-- Hand-written, applied last, never autogenerated.
--
-- Three implementation details decide whether this works or quietly does
-- nothing (build guide, §"Data layer and row-level security"):
--
--   1. The application must connect as a role that is neither the table owner
--      nor holds BYPASSRLS. That is sourcehub_app, created in 000. These
--      scripts run as the superuser, which ALWAYS bypasses RLS — so verifying
--      isolation by querying as postgres proves nothing.
--   2. SET LOCAL only lasts a transaction, so every session opens one before
--      setting the org context.
--   3. current_setting(..., true) with the missing-ok flag, so an unset context
--      returns NULL and the policy fails closed rather than raising.
--
-- A FOURTH detail, learned the hard way on this schema: a policy with no FOR
-- clause defaults to FOR ALL, and for an ALL policy Postgres reuses the USING
-- expression as the WITH CHECK for INSERT and UPDATE. Permissive policies OR
-- together, so a broad "who can read this row" predicate silently becomes
-- "who can write this row" — a tenant could insert its own approval and
-- self-onboard its network.
--
-- Therefore: every read policy below is explicitly FOR SELECT, and every write
-- path has its own narrower policy. A table with no INSERT policy cannot be
-- inserted into at all, which is the correct default.
--
-- SourceHub has TWO axes, and the blueprint calls conflating them "the most
-- likely source of a data-leak bug in this product":
--
--   account axis : one client from another, one partner from another
--   network axis : an aggregator belongs to exactly one partner and must be
--                  invisible to every other partner — including partners
--                  bidding on the same request
-- ============================================================================

-- ---------------------------------------------------------------------------
-- SECURITY DEFINER helpers.
--
-- A policy ON organisation that subqueries organisation would re-enter its own
-- policy and recurse. These run as the owner, so they see every row, and are
-- the only sanctioned way to escape the predicate.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION current_org_parent_id() RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT parent_org_id FROM organisation WHERE id = current_org_id()
$fn$;

CREATE OR REPLACE FUNCTION current_org_kind() RETURNS org_kind
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT kind FROM organisation WHERE id = current_org_id()
$fn$;

-- Is p_org_id inside the current org's own network?
CREATE OR REPLACE FUNCTION org_in_my_network(p_org_id uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT EXISTS (SELECT 1 FROM organisation o
                  WHERE o.id = p_org_id AND o.parent_org_id = current_org_id())
$fn$;

-- A client reaches a supplier ONLY by traversing a contract it owns. That is
-- what makes supplier attribution safe to expose (blueprint, figure 3).
CREATE OR REPLACE FUNCTION org_visible_via_contract(p_org_id uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT EXISTS (
    SELECT 1
    FROM   contract c
    LEFT   JOIN task t ON t.contract_id = c.id
    WHERE  (c.client_org_id = current_org_id() OR c.partner_org_id = current_org_id())
      AND  (c.client_org_id = p_org_id OR c.partner_org_id = p_org_id
            OR t.assignee_org_id = p_org_id)
  )
$fn$;

CREATE OR REPLACE FUNCTION contract_is_visible(p_contract_id uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM contract c
    WHERE c.id = p_contract_id
      AND (c.client_org_id  = current_org_id()
        OR c.partner_org_id = current_org_id()
        OR EXISTS (SELECT 1 FROM task t
                    WHERE t.contract_id = c.id
                      AND t.assignee_org_id = current_org_id()))
  )
$fn$;

-- Is the current org the delivering partner on this contract?
CREATE OR REPLACE FUNCTION contract_is_mine_as_partner(p_contract_id uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT EXISTS (SELECT 1 FROM contract c
                  WHERE c.id = p_contract_id AND c.partner_org_id = current_org_id())
$fn$;

DO $g$
DECLARE f text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'current_org_parent_id()', 'current_org_kind()',
    'org_in_my_network(uuid)', 'org_visible_via_contract(uuid)',
    'contract_is_visible(uuid)', 'contract_is_mine_as_partner(uuid)'
  ] LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC', f);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO sourcehub_app, sourcehub_readonly', f);
  END LOOP;
END
$g$;


-- ============================================================================
-- Identity
-- ============================================================================

ALTER TABLE organisation ENABLE ROW LEVEL SECURITY;
ALTER TABLE organisation FORCE  ROW LEVEL SECURITY;

CREATE POLICY organisation_select ON organisation FOR SELECT
  USING (
       is_platform_admin()                          -- Ops sees every account
    OR id            = current_org_id()             -- itself
    OR parent_org_id = current_org_id()             -- NETWORK AXIS: its own suppliers
    OR id            = current_org_parent_id()      -- a supplier sees its tenant
    OR org_visible_via_contract(id)                 -- a counterparty on a shared contract
  );

-- Only Ops creates an organisation. A tenant asks; it does not create.
CREATE POLICY organisation_insert ON organisation FOR INSERT
  WITH CHECK (is_platform_admin());

CREATE POLICY organisation_update ON organisation FOR UPDATE
  USING      (is_platform_admin() OR id = current_org_id())
  WITH CHECK (is_platform_admin() OR id = current_org_id());


-- Profiles: readable with their organisation, writable by that org or Ops.
ALTER TABLE client_profile     ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_profile     FORCE  ROW LEVEL SECURITY;
ALTER TABLE tenant_profile     ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_profile     FORCE  ROW LEVEL SECURITY;
ALTER TABLE aggregator_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE aggregator_profile FORCE  ROW LEVEL SECURITY;
ALTER TABLE business_profile   ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_profile   FORCE  ROW LEVEL SECURITY;
ALTER TABLE sponsor_profile    ENABLE ROW LEVEL SECURITY;
ALTER TABLE sponsor_profile    FORCE  ROW LEVEL SECURITY;

CREATE POLICY client_profile_select ON client_profile FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id()
         OR org_id = current_org_parent_id() OR org_in_my_network(org_id)
         OR org_visible_via_contract(org_id));
CREATE POLICY client_profile_write ON client_profile FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());

CREATE POLICY tenant_profile_select ON tenant_profile FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id()
         OR org_id = current_org_parent_id() OR org_in_my_network(org_id)
         OR org_visible_via_contract(org_id));
CREATE POLICY tenant_profile_write ON tenant_profile FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());

CREATE POLICY aggregator_profile_select ON aggregator_profile FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id()
         OR org_id = current_org_parent_id() OR org_in_my_network(org_id)
         OR org_visible_via_contract(org_id));
CREATE POLICY aggregator_profile_write ON aggregator_profile FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());

CREATE POLICY business_profile_select ON business_profile FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id()
         OR org_id = current_org_parent_id() OR org_in_my_network(org_id)
         OR org_visible_via_contract(org_id));
CREATE POLICY business_profile_write ON business_profile FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());

CREATE POLICY sponsor_profile_select ON sponsor_profile FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id()
         OR org_id = current_org_parent_id() OR org_in_my_network(org_id));
CREATE POLICY sponsor_profile_write ON sponsor_profile FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());


-- ---------------------------------------------------------------------------
-- app_user — visible to the orgs the user holds a live grant in.
--
-- The login path cannot use this: authentication happens BEFORE an org context
-- exists. That is what authenticate_lookup() at the bottom of this file is for.
-- ---------------------------------------------------------------------------
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_user FORCE  ROW LEVEL SECURITY;

CREATE POLICY app_user_select ON app_user FOR SELECT
  USING (
       is_platform_admin()
    OR id = current_user_id()                       -- yourself, always
    OR EXISTS (SELECT 1 FROM user_role_grant g
                WHERE g.user_id = app_user.id
                  AND g.org_id  = current_org_id()
                  AND g.revoked_at IS NULL)
  );

-- Creating a user requires an authenticated context. The user.invite
-- capability is enforced in the service layer; this is the floor beneath it.
CREATE POLICY app_user_insert ON app_user FOR INSERT
  WITH CHECK (is_platform_admin() OR current_org_id() IS NOT NULL);

CREATE POLICY app_user_update ON app_user FOR UPDATE
  USING (
       is_platform_admin()
    OR id = current_user_id()
    OR EXISTS (SELECT 1 FROM user_role_grant g
                WHERE g.user_id = app_user.id AND g.org_id = current_org_id()
                  AND g.revoked_at IS NULL)
  );

ALTER TABLE user_role_grant ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_role_grant FORCE  ROW LEVEL SECURITY;

CREATE POLICY user_role_grant_select ON user_role_grant FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id() OR user_id = current_user_id());
-- You may only grant roles inside your own organisation.
CREATE POLICY user_role_grant_write ON user_role_grant FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());

ALTER TABLE user_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_session FORCE  ROW LEVEL SECURITY;
CREATE POLICY user_session_own ON user_session FOR ALL
  USING      (user_id = current_user_id() OR is_platform_admin())
  WITH CHECK (user_id = current_user_id() OR is_platform_admin());

ALTER TABLE user_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_token FORCE  ROW LEVEL SECURITY;
CREATE POLICY user_token_own ON user_token FOR ALL
  USING      (user_id = current_user_id() OR is_platform_admin())
  WITH CHECK (user_id = current_user_id() OR is_platform_admin());

ALTER TABLE user_mfa ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_mfa FORCE  ROW LEVEL SECURITY;
CREATE POLICY user_mfa_own ON user_mfa FOR ALL
  USING      (user_id = current_user_id())
  WITH CHECK (user_id = current_user_id());

-- role and permission are reference data: readable by all, written by Ops only.
ALTER TABLE role ENABLE ROW LEVEL SECURITY;
ALTER TABLE role FORCE  ROW LEVEL SECURITY;
CREATE POLICY role_select ON role FOR SELECT
  USING (is_system OR org_id = current_org_id() OR is_platform_admin());
CREATE POLICY role_write ON role FOR ALL
  USING      (is_platform_admin() OR (NOT is_system AND org_id = current_org_id()))
  WITH CHECK (is_platform_admin() OR (NOT is_system AND org_id = current_org_id()));


-- ============================================================================
-- Onboarding — the approval queue
--
-- A tenant sees the requests it raised and may file new ones. It may NOT write
-- a decision: onboarding_approval accepts inserts from Ops alone. That single
-- policy is what stops a tenant self-approving its own network.
-- ============================================================================

ALTER TABLE onboarding_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_request FORCE  ROW LEVEL SECURITY;

CREATE POLICY onboarding_request_select ON onboarding_request FOR SELECT
  USING (
       is_platform_admin()
    OR requester_org_id = current_org_id()
    OR parent_org_id    = current_org_id()
    OR created_org_id   = current_org_id()          -- the new org sees its own origin
  );

-- You may only file a request in your own name.
CREATE POLICY onboarding_request_insert ON onboarding_request FOR INSERT
  WITH CHECK (
    is_platform_admin()
    OR (requester_org_id = current_org_id() AND requester_user_id = current_user_id())
  );

-- The requester may edit a draft or withdraw; Ops may move it through review.
CREATE POLICY onboarding_request_update ON onboarding_request FOR UPDATE
  USING      (is_platform_admin() OR requester_org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR requester_org_id = current_org_id());

ALTER TABLE onboarding_approval ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_approval FORCE  ROW LEVEL SECURITY;

CREATE POLICY onboarding_approval_select ON onboarding_approval FOR SELECT
  USING (
       is_platform_admin()
    OR EXISTS (SELECT 1 FROM onboarding_request r
                WHERE r.id = onboarding_approval.request_id
                  AND (r.requester_org_id = current_org_id()
                    OR r.parent_org_id    = current_org_id()))
  );

-- ONLY Ops decides. No UPDATE or DELETE policy exists, so the record is
-- append-only at the policy level as well as by intent.
CREATE POLICY onboarding_approval_insert ON onboarding_approval FOR INSERT
  WITH CHECK (is_platform_admin());

ALTER TABLE onboarding_document ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_document FORCE  ROW LEVEL SECURITY;
CREATE POLICY onboarding_document_select ON onboarding_document FOR SELECT
  USING (
       is_platform_admin()
    OR EXISTS (SELECT 1 FROM onboarding_request r
                WHERE r.id = onboarding_document.request_id
                  AND (r.requester_org_id = current_org_id()
                    OR r.parent_org_id    = current_org_id()))
  );
CREATE POLICY onboarding_document_insert ON onboarding_document FOR INSERT
  WITH CHECK (
       is_platform_admin()
    OR EXISTS (SELECT 1 FROM onboarding_request r
                WHERE r.id = onboarding_document.request_id
                  AND r.requester_org_id = current_org_id())
  );

ALTER TABLE invitation ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitation FORCE  ROW LEVEL SECURITY;
CREATE POLICY invitation_select ON invitation FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id());
CREATE POLICY invitation_write ON invitation FOR ALL
  USING      (is_platform_admin() OR org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR org_id = current_org_id());


-- ============================================================================
-- Marketplace
-- ============================================================================

ALTER TABLE request ENABLE ROW LEVEL SECURITY;
ALTER TABLE request FORCE  ROW LEVEL SECURITY;

CREATE POLICY request_select ON request FOR SELECT
  USING (
       is_platform_admin()
    OR client_org_id = current_org_id()             -- the buyer
    OR (status IN ('published','proposals_received')  -- the open marketplace
        AND current_org_kind() = 'tenant')
    OR EXISTS (SELECT 1 FROM contract c              -- the awarded partner
                WHERE c.request_id = request.id
                  AND c.partner_org_id = current_org_id())
  );

-- Only the buying client writes its own request.
CREATE POLICY request_insert ON request FOR INSERT
  WITH CHECK (client_org_id = current_org_id());
CREATE POLICY request_update ON request FOR UPDATE
  USING      (is_platform_admin() OR client_org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR client_org_id = current_org_id());

ALTER TABLE proposal ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal FORCE  ROW LEVEL SECURITY;

-- A partner sees its own bid and never a competitor's.
CREATE POLICY proposal_select ON proposal FOR SELECT
  USING (
       is_platform_admin()
    OR partner_org_id = current_org_id()
    OR EXISTS (SELECT 1 FROM request r
                WHERE r.id = proposal.request_id AND r.client_org_id = current_org_id())
  );

-- Only the bidding partner may submit or withdraw its own bid...
CREATE POLICY proposal_insert ON proposal FOR INSERT
  WITH CHECK (partner_org_id = current_org_id());
-- ...but the client must be able to mark one accepted and the rest rejected.
CREATE POLICY proposal_update ON proposal FOR UPDATE
  USING (
       is_platform_admin()
    OR partner_org_id = current_org_id()
    OR EXISTS (SELECT 1 FROM request r
                WHERE r.id = proposal.request_id AND r.client_org_id = current_org_id())
  );

ALTER TABLE proposal_resource ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal_resource FORCE  ROW LEVEL SECURITY;
CREATE POLICY proposal_resource_select ON proposal_resource FOR SELECT
  USING (EXISTS (SELECT 1 FROM proposal p WHERE p.id = proposal_resource.proposal_id));
CREATE POLICY proposal_resource_write ON proposal_resource FOR ALL
  USING      (EXISTS (SELECT 1 FROM proposal p
                       WHERE p.id = proposal_resource.proposal_id
                         AND p.partner_org_id = current_org_id()))
  WITH CHECK (EXISTS (SELECT 1 FROM proposal p
                       WHERE p.id = proposal_resource.proposal_id
                         AND p.partner_org_id = current_org_id()));

ALTER TABLE request_sample ENABLE ROW LEVEL SECURITY;
ALTER TABLE request_sample FORCE  ROW LEVEL SECURITY;

-- A sample is visible exactly where its request is (request_select, inlined
-- against the parent row the way onboarding_document does it).
CREATE POLICY request_sample_select ON request_sample FOR SELECT
  USING (
       is_platform_admin()
    OR EXISTS (SELECT 1 FROM request r
                WHERE r.id = request_sample.request_id
                  AND r.deleted_at IS NULL
                  AND (r.client_org_id = current_org_id()          -- the buyer
                    OR (r.status IN ('published','proposals_received')
                        AND current_org_kind() = 'tenant')          -- the open marketplace
                    OR EXISTS (SELECT 1 FROM contract c             -- the awarded partner
                                WHERE c.request_id = r.id
                                  AND c.partner_org_id = current_org_id())))
  );

-- Only the buying client attaches samples; append-only (no UPDATE/DELETE policy).
CREATE POLICY request_sample_insert ON request_sample FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM request r
                       WHERE r.id = request_sample.request_id
                         AND r.client_org_id = current_org_id()));


-- ============================================================================
-- Delivery — the reference policy from the build guide, verbatim in shape
-- ============================================================================

ALTER TABLE contract ENABLE ROW LEVEL SECURITY;
ALTER TABLE contract FORCE  ROW LEVEL SECURITY;

CREATE POLICY contract_select ON contract FOR SELECT
  USING (
       is_platform_admin()
    OR client_org_id  = current_org_id()            -- the buying client
    OR partner_org_id = current_org_id()            -- the delivering partner
    OR EXISTS (                                     -- a supplier on one of its tasks
         SELECT 1 FROM task t
         WHERE t.contract_id = contract.id
           AND t.assignee_org_id = current_org_id())
  );

-- A contract comes into being when the client awards.
CREATE POLICY contract_insert ON contract FOR INSERT
  WITH CHECK (is_platform_admin() OR client_org_id = current_org_id());
CREATE POLICY contract_update ON contract FOR UPDATE
  USING (is_platform_admin() OR client_org_id = current_org_id()
         OR partner_org_id = current_org_id());

ALTER TABLE task ENABLE ROW LEVEL SECURITY;
ALTER TABLE task FORCE  ROW LEVEL SECURITY;

CREATE POLICY task_select ON task FOR SELECT
  USING (is_platform_admin() OR assignee_org_id = current_org_id()
         OR contract_is_visible(contract_id));

-- Only the delivering partner breaks a contract into tasks.
CREATE POLICY task_insert ON task FOR INSERT
  WITH CHECK (is_platform_admin() OR contract_is_mine_as_partner(contract_id));
-- The partner reassigns; the supplier moves its own task's status.
CREATE POLICY task_update ON task FOR UPDATE
  USING (is_platform_admin() OR contract_is_mine_as_partner(contract_id)
         OR assignee_org_id = current_org_id());

ALTER TABLE submission ENABLE ROW LEVEL SECURITY;
ALTER TABLE submission FORCE  ROW LEVEL SECURITY;
CREATE POLICY submission_select ON submission FOR SELECT
  USING (
       is_platform_admin()
    OR supplier_org_id = current_org_id()
    OR EXISTS (SELECT 1 FROM task t
                WHERE t.id = submission.task_id AND contract_is_visible(t.contract_id))
  );
-- A supplier submits its own work and nobody else's.
CREATE POLICY submission_write ON submission FOR ALL
  USING      (is_platform_admin() OR supplier_org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR supplier_org_id = current_org_id());

ALTER TABLE asset ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset FORCE  ROW LEVEL SECURITY;
CREATE POLICY asset_select ON asset FOR SELECT
  USING (
       is_platform_admin()
    OR EXISTS (SELECT 1 FROM submission s
                JOIN task t ON t.id = s.task_id
               WHERE s.id = asset.submission_id
                 AND (s.supplier_org_id = current_org_id()
                   OR contract_is_visible(t.contract_id)))
  );
CREATE POLICY asset_write ON asset FOR ALL
  USING      (is_platform_admin()
              OR EXISTS (SELECT 1 FROM submission s WHERE s.id = asset.submission_id
                          AND s.supplier_org_id = current_org_id()))
  WITH CHECK (is_platform_admin()
              OR EXISTS (SELECT 1 FROM submission s WHERE s.id = asset.submission_id
                          AND s.supplier_org_id = current_org_id()));

ALTER TABLE consent_artefact ENABLE ROW LEVEL SECURITY;
ALTER TABLE consent_artefact FORCE  ROW LEVEL SECURITY;
CREATE POLICY consent_artefact_select ON consent_artefact FOR SELECT
  USING (is_platform_admin() OR contract_is_visible(contract_id));
CREATE POLICY consent_artefact_insert ON consent_artefact FOR INSERT
  WITH CHECK (is_platform_admin() OR contract_is_visible(contract_id));


-- ============================================================================
-- QA
-- ============================================================================

ALTER TABLE qa_review ENABLE ROW LEVEL SECURITY;
ALTER TABLE qa_review FORCE  ROW LEVEL SECURITY;
CREATE POLICY qa_review_select ON qa_review FOR SELECT
  USING (
       is_platform_admin()
    OR reviewer_org_id = current_org_id()
    OR EXISTS (SELECT 1 FROM submission s
                JOIN task t ON t.id = s.task_id
               WHERE s.id = qa_review.submission_id
                 AND (s.supplier_org_id = current_org_id()
                   OR contract_is_visible(t.contract_id)))
  );
-- You may only record a review in your own name. Which GATE you may record is
-- a capability check in the service layer; that you cannot forge another org's
-- verdict is enforced here.
CREATE POLICY qa_review_insert ON qa_review FOR INSERT
  WITH CHECK (reviewer_org_id = current_org_id());

ALTER TABLE rubric ENABLE ROW LEVEL SECURITY;
ALTER TABLE rubric FORCE  ROW LEVEL SECURITY;
CREATE POLICY rubric_select ON rubric FOR SELECT
  USING (is_platform_admin()
         OR EXISTS (SELECT 1 FROM request r WHERE r.id = rubric.request_id));
CREATE POLICY rubric_write ON rubric FOR ALL
  USING      (EXISTS (SELECT 1 FROM request r WHERE r.id = rubric.request_id
                       AND r.client_org_id = current_org_id()))
  WITH CHECK (EXISTS (SELECT 1 FROM request r WHERE r.id = rubric.request_id
                       AND r.client_org_id = current_org_id()));

ALTER TABLE gold_set ENABLE ROW LEVEL SECURITY;
ALTER TABLE gold_set FORCE  ROW LEVEL SECURITY;
CREATE POLICY gold_set_select ON gold_set FOR SELECT
  USING (is_platform_admin() OR owner_org_id = current_org_id());
CREATE POLICY gold_set_write ON gold_set FOR ALL
  USING      (owner_org_id = current_org_id())
  WITH CHECK (owner_org_id = current_org_id());


-- ============================================================================
-- Network
-- ============================================================================

ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipment FORCE  ROW LEVEL SECURITY;

CREATE POLICY equipment_select ON equipment FOR SELECT
  USING (
       is_platform_admin()
    OR sponsor_org_id = current_org_id()            -- the sponsor's own inventory
    OR org_in_my_network(sponsor_org_id)            -- NETWORK AXIS: the sponsor's tenant
    OR EXISTS (SELECT 1 FROM loan l                 -- a borrower on a live loan
                WHERE l.equipment_id = equipment.id
                  AND l.requester_org_id = current_org_id())
  );
-- Only the sponsor manages its own inventory.
CREATE POLICY equipment_write ON equipment FOR ALL
  USING      (is_platform_admin() OR sponsor_org_id = current_org_id())
  WITH CHECK (is_platform_admin() OR sponsor_org_id = current_org_id());

ALTER TABLE loan ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan FORCE  ROW LEVEL SECURITY;
CREATE POLICY loan_select ON loan FOR SELECT
  USING (
       is_platform_admin()
    OR sponsor_org_id   = current_org_id()
    OR requester_org_id = current_org_id()
    OR org_in_my_network(sponsor_org_id)
  );
-- The borrower raises the request...
CREATE POLICY loan_insert ON loan FOR INSERT
  WITH CHECK (requester_org_id = current_org_id());
-- ...and the sponsor decides it.
CREATE POLICY loan_update ON loan FOR UPDATE
  USING (is_platform_admin() OR sponsor_org_id = current_org_id()
         OR requester_org_id = current_org_id());

ALTER TABLE crowd_worker ENABLE ROW LEVEL SECURITY;
ALTER TABLE crowd_worker FORCE  ROW LEVEL SECURITY;

-- A roster is the aggregator's own. Its tenant may see it; no one else can,
-- and no client ever does.
CREATE POLICY crowd_worker_select ON crowd_worker FOR SELECT
  USING (is_platform_admin() OR aggregator_org_id = current_org_id()
         OR org_in_my_network(aggregator_org_id));
CREATE POLICY crowd_worker_write ON crowd_worker FOR ALL
  USING      (aggregator_org_id = current_org_id())
  WITH CHECK (aggregator_org_id = current_org_id());

ALTER TABLE rating ENABLE ROW LEVEL SECURITY;
ALTER TABLE rating FORCE  ROW LEVEL SECURITY;
CREATE POLICY rating_select ON rating FOR SELECT
  USING (is_platform_admin() OR from_org_id = current_org_id()
         OR to_org_id = current_org_id() OR contract_is_visible(contract_id));
-- You rate in your own name only.
CREATE POLICY rating_insert ON rating FOR INSERT
  WITH CHECK (from_org_id = current_org_id());


-- ============================================================================
-- Ledger — an org reads its own money and nobody else's. Only Ops writes.
-- ============================================================================

ALTER TABLE invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice FORCE  ROW LEVEL SECURITY;
CREATE POLICY invoice_select ON invoice FOR SELECT
  USING (is_platform_admin() OR party_org_id = current_org_id());
CREATE POLICY invoice_write ON invoice FOR ALL
  USING (is_platform_admin()) WITH CHECK (is_platform_admin());

ALTER TABLE ledger_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_account FORCE  ROW LEVEL SECURITY;
CREATE POLICY ledger_account_select ON ledger_account FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id());
CREATE POLICY ledger_account_write ON ledger_account FOR ALL
  USING (is_platform_admin()) WITH CHECK (is_platform_admin());

ALTER TABLE ledger_transaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_transaction FORCE  ROW LEVEL SECURITY;
CREATE POLICY ledger_transaction_select ON ledger_transaction FOR SELECT
  USING (is_platform_admin() OR (contract_id IS NOT NULL AND contract_is_visible(contract_id)));
CREATE POLICY ledger_transaction_write ON ledger_transaction FOR ALL
  USING (is_platform_admin()) WITH CHECK (is_platform_admin());

ALTER TABLE ledger_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entry FORCE  ROW LEVEL SECURITY;
CREATE POLICY ledger_entry_select ON ledger_entry FOR SELECT
  USING (is_platform_admin()
         OR EXISTS (SELECT 1 FROM ledger_account a
                     WHERE a.id = ledger_entry.account_id AND a.org_id = current_org_id()));
-- Money is written by the platform alone. No UPDATE or DELETE policy exists;
-- a correction is a reversing transaction.
CREATE POLICY ledger_entry_insert ON ledger_entry FOR INSERT
  WITH CHECK (is_platform_admin());


-- ============================================================================
-- Notify and audit
-- ============================================================================

ALTER TABLE notification ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification FORCE  ROW LEVEL SECURITY;
CREATE POLICY notification_select ON notification FOR SELECT
  USING (org_id = current_org_id() AND (user_id IS NULL OR user_id = current_user_id()));
-- Any authenticated actor may notify another org (awarding a contract notifies
-- the winner). Marking one read is an update by its recipient.
CREATE POLICY notification_insert ON notification FOR INSERT
  WITH CHECK (current_org_id() IS NOT NULL);
CREATE POLICY notification_update ON notification FOR UPDATE
  USING (org_id = current_org_id());

ALTER TABLE audit_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_event FORCE  ROW LEVEL SECURITY;

-- You see the events you caused, and the events touching things you can see.
CREATE POLICY audit_event_select ON audit_event FOR SELECT
  USING (is_platform_admin() OR actor_org_id = current_org_id()
         OR current_org_id() = ANY (scope));
-- Append-only: an INSERT policy and deliberately no UPDATE or DELETE policy,
-- backed by the rewrite rules in 090.
CREATE POLICY audit_event_insert ON audit_event FOR INSERT
  WITH CHECK (current_org_id() IS NOT NULL OR is_platform_admin());

ALTER TABLE legal_hold ENABLE ROW LEVEL SECURITY;
ALTER TABLE legal_hold FORCE  ROW LEVEL SECURITY;
CREATE POLICY legal_hold_select ON legal_hold FOR SELECT
  USING (is_platform_admin() OR org_id = current_org_id());
CREATE POLICY legal_hold_write ON legal_hold FOR ALL
  USING (is_platform_admin()) WITH CHECK (is_platform_admin());


-- ============================================================================
-- Authentication happens before an org context exists.
--
-- The login path needs to read app_user by email with no app.org_id set — and
-- app_user_select correctly denies exactly that. This function is the one
-- sanctioned hole: it runs as the owner, takes an email, and returns only what
-- the credential check needs. It cannot enumerate or list anything.
-- ============================================================================
CREATE OR REPLACE FUNCTION authenticate_lookup(p_email citext)
RETURNS TABLE (
  user_id uuid, password_hash text, password_algo text, status user_status,
  locked_until timestamptz, failed_login_count smallint, must_change_password boolean
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT u.id, u.password_hash, u.password_algo, u.status,
         u.locked_until, u.failed_login_count, u.must_change_password
  FROM   app_user u
  WHERE  u.email = p_email AND u.deleted_at IS NULL
$fn$;

REVOKE EXECUTE ON FUNCTION authenticate_lookup(citext) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION authenticate_lookup(citext) TO sourcehub_app;

-- Recording an attempt and moving the lockout counters likewise happens with
-- no org context.
CREATE OR REPLACE FUNCTION record_login_attempt(
  p_email citext, p_user_id uuid, p_succeeded boolean,
  p_failure_code text, p_ip inet, p_user_agent text,
  p_lock_threshold int DEFAULT 5, p_lock_for interval DEFAULT interval '15 minutes'
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
BEGIN
  INSERT INTO login_attempt (email, user_id, succeeded, failure_code, ip_address, user_agent)
  VALUES (p_email, p_user_id, p_succeeded, p_failure_code, p_ip, p_user_agent);

  IF p_user_id IS NULL THEN RETURN; END IF;

  IF p_succeeded THEN
    UPDATE app_user
       SET failed_login_count = 0, locked_until = NULL, last_login_at = now()
     WHERE id = p_user_id;
  ELSE
    UPDATE app_user
       SET failed_login_count = failed_login_count + 1,
           locked_until = CASE WHEN failed_login_count + 1 >= p_lock_threshold
                               THEN now() + p_lock_for ELSE locked_until END,
           status = CASE WHEN failed_login_count + 1 >= p_lock_threshold
                         THEN 'locked'::user_status ELSE status END
     WHERE id = p_user_id;
  END IF;
END
$fn$;

REVOKE EXECUTE ON FUNCTION record_login_attempt(citext,uuid,boolean,text,inet,text,int,interval) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION record_login_attempt(citext,uuid,boolean,text,inet,text,int,interval) TO sourcehub_app;

-- The onboarding approval runs with the CALLER's rights, so every RLS policy
-- above applies inside it. A tenant calling it fails on organisation_insert.
GRANT EXECUTE ON FUNCTION user_organisations(uuid)     TO sourcehub_app;
GRANT EXECUTE ON FUNCTION user_capabilities(uuid,uuid) TO sourcehub_app;
GRANT EXECUTE ON FUNCTION user_requires_mfa(uuid,uuid) TO sourcehub_app;
GRANT EXECUTE ON FUNCTION approve_onboarding_request(uuid,uuid,uuid,text,text,interval) TO sourcehub_app;
GRANT EXECUTE ON FUNCTION write_audit_event(text,text,uuid[],jsonb,uuid,uuid) TO sourcehub_app;
