import type {
  Certification,
  AppealRecord,
  HomeSummary,
  KitCustody,
  LearningModule,
  NotificationItem,
  Task,
  WalletSummary,
} from '@/types/domain';
import { MINIO_UPLOAD_TEST_BUCKET, MINIO_UPLOAD_TEST_TASK_ID } from '@/features/minio-upload-test/minio-upload-test-task';

const now = Date.now();
const minioUploadTestRequiredCount = Number(MINIO_UPLOAD_TEST_TASK_ID.split('-').at(-1));

export const mockTasks: Task[] = [
  {
    id: MINIO_UPLOAD_TEST_TASK_ID,
    title: `Upload ${minioUploadTestRequiredCount} Images`,
    category: 'Storage / MinIO',
    project: 'MinIO Upload Reliability Test',
    campaignId: 'campaign-minio-upload-test',
    location: 'Expo Go test device',
    pay: 125,
    currency: 'INR',
    estimatedMinutes: 10,
    difficulty: 'starter',
    status: 'available',
    taskType: 'capture',
    progress: 0,
    requiredMedia: ['image'],
    requiredUploadCount: minioUploadTestRequiredCount,
    allowedFileTypes: ['jpg', 'jpeg', 'png'],
    storageBucket: MINIO_UPLOAD_TEST_BUCKET,
    slotsRemaining: 1,
    dueAt: new Date(now + 1000 * 60 * 60 * 24).toISOString(),
    checklist: [
      `Upload exactly ${minioUploadTestRequiredCount} jpg, jpeg or png images.`,
      'Wait for each image to reach uploaded before submitting the task.',
      'Retry failed images from the task progress panel.',
    ],
    description:
      `Upload exactly ${minioUploadTestRequiredCount} images to verify that MinIO storage and the upload flow are working correctly.`,
    qualityBar: `${minioUploadTestRequiredCount} distinct images, successful upload status for each item, no duplicate upload records on retry.`,
  },
  {
    id: 'task-market-photos',
    title: 'Market storefront image set',
    category: 'Retail / Storefront',
    project: 'Karnataka Retail Dataset',
    campaignId: 'campaign-karnataka-retail',
    location: 'Indiranagar, Bengaluru',
    pay: 180,
    currency: 'INR',
    estimatedMinutes: 18,
    difficulty: 'starter',
    status: 'available',
    taskType: 'capture',
    progress: 0.18,
    requiredMedia: ['image'],
    certificationRequired: 'Visual QA Basics',
    distanceKm: 1.8,
    slotsRemaining: 12,
    dueAt: new Date(now + 1000 * 60 * 60 * 9).toISOString(),
    checklist: [
      'Capture the full storefront in daylight.',
      'Avoid faces, number plates, and private interiors.',
      'Submit at least one clear image before leaving the location.',
    ],
    description:
      'Collect storefront evidence for retail taxonomy validation. Images are reviewed by tenant QA before payout.',
    qualityBar: 'Readable signboard, stable frame, no private personal data.',
  },
  {
    id: 'task-traffic-video',
    title: 'Short road-safety video',
    category: 'Road Safety / Mobility',
    project: 'Urban Mobility Safety Campaign',
    campaignId: 'campaign-urban-mobility',
    location: 'MG Road signal',
    pay: 260,
    currency: 'INR',
    estimatedMinutes: 22,
    difficulty: 'standard',
    status: 'in_progress',
    taskType: 'capture',
    progress: 0.46,
    requiredMedia: ['video'],
    distanceKm: 3.2,
    slotsRemaining: 5,
    dueAt: new Date(now + 1000 * 60 * 60 * 14).toISOString(),
    checklist: [
      'Record a steady 10-20 second clip.',
      'Do not film restricted facilities.',
      'Upload from queue when connectivity returns.',
    ],
    description:
      'Capture public-road conditions for a safety data initiative. Demo duplicate and mock QC checks run locally in this prototype.',
    qualityBar: 'Stable clip, road context visible, no zooming into people.',
  },
  {
    id: 'task-industrial-equipment-video',
    title: 'Industrial Equipment Inspection Video',
    category: 'Industry / Manufacturing',
    project: 'Factory Operations Demo Dataset',
    campaignId: 'campaign-industrial-inspection',
    location: 'Partner manufacturing floor',
    pay: 920,
    currency: 'INR',
    estimatedMinutes: 38,
    difficulty: 'advanced',
    status: 'available',
    taskType: 'capture',
    progress: 0.08,
    requiredMedia: ['video'],
    requiredDurationMs: 5 * 60_000,
    certificationRequired: 'Field Privacy and Consent',
    slotsRemaining: 4,
    dueAt: new Date(now + 1000 * 60 * 60 * 20).toISOString(),
    checklist: [
      'Record at least 5 minutes of industrial machinery or equipment during normal operation.',
      'Keep machinery in frame and clearly visible throughout the recording.',
      'Capture normal operating conditions and relevant equipment movement where safe.',
      'Avoid excessive camera movement and unrelated areas.',
      'Follow workplace safety requirements; do not enter restricted or hazardous zones.',
    ],
    description:
      'Record industrial machinery or equipment during normal operation while keeping the equipment clearly visible throughout the recording.',
    qualityBar:
      'Adequate lighting, steady framing, equipment visible, no unrelated footage and no requirement to approach dangerous machinery.',
  },
  {
    id: 'task-label-shelves',
    title: 'Shelf image label confirmation',
    category: 'Retail / Annotation',
    project: 'Retail Shelf Ontology',
    campaignId: 'campaign-retail-shelf',
    location: 'Remote batch',
    pay: 95,
    currency: 'INR',
    estimatedMinutes: 11,
    difficulty: 'starter',
    status: 'available',
    taskType: 'annotation',
    progress: 0.62,
    requiredMedia: ['image'],
    certificationRequired: 'Visual QA Basics',
    slotsRemaining: 42,
    dueAt: new Date(now + 1000 * 60 * 60 * 18).toISOString(),
    checklist: ['Review the supplied frame.', 'Confirm or edit the pre-label box.', 'Submit only if the product is visible.'],
    description:
      'Confirm a lightweight mobile annotation supplied by the Edge Auto-label queue. Advanced polygon edits remain in the Crowd Visual IDE.',
    qualityBar: 'One clear label, box aligned to the visible shelf product.',
  },
  {
    id: 'task-audio-signals',
    title: 'Ambient audio transcription',
    category: 'Audio / Transcription',
    project: 'Acoustic Context Dataset',
    campaignId: 'campaign-acoustic-context',
    location: 'Metro station exterior',
    pay: 140,
    currency: 'INR',
    estimatedMinutes: 12,
    difficulty: 'starter',
    status: 'available',
    taskType: 'transcription',
    progress: 0.24,
    requiredMedia: ['audio'],
    slotsRemaining: 18,
    dueAt: new Date(now + 1000 * 60 * 60 * 26).toISOString(),
    checklist: ['Listen to the short segment.', 'Edit the Edge pre-transcription.', 'Do not invent WER or final QC results.'],
    description:
      'Review a short ambient sample and submit an editable transcript. Final scoring remains backend-authoritative.',
    qualityBar: 'Transcript matches audible public-environment speech or marks inaudible segments.',
  },
  {
    id: 'task-kit-rack-survey',
    title: 'Kit rack condition survey',
    category: 'Devices / Custody',
    project: 'Device Custody Audit',
    campaignId: 'campaign-device-custody',
    location: 'Partner hub BLR-04',
    pay: 110,
    currency: 'INR',
    estimatedMinutes: 9,
    difficulty: 'starter',
    status: 'available',
    taskType: 'survey',
    progress: 0.1,
    requiredMedia: ['image'],
    certificationRequired: 'Field Privacy and Consent',
    slotsRemaining: 8,
    dueAt: new Date(now + 1000 * 60 * 60 * 30).toISOString(),
    checklist: ['Scan or type the rack identifier.', 'Record condition.', 'Attach auto-QC photo before submit.'],
    description: 'Submit a mobile survey for assigned rack or kit condition.',
    qualityBar: 'Identifier is readable and condition notes are specific.',
  },
  {
    id: 'task-sxs-answer-rating',
    title: 'Side-by-side answer rating',
    category: 'AI Evaluation',
    project: 'Model Evaluation Wave 12',
    campaignId: 'campaign-model-eval-12',
    location: 'Remote batch',
    pay: 75,
    currency: 'INR',
    estimatedMinutes: 7,
    difficulty: 'standard',
    status: 'available',
    taskType: 'sxs',
    progress: 0.35,
    requiredMedia: [],
    certificationRequired: 'Model Evaluation Basics',
    slotsRemaining: 31,
    dueAt: new Date(now + 1000 * 60 * 60 * 12).toISOString(),
    checklist: ['Read both options.', 'Apply the rubric.', 'Write a short justification where required.'],
    description: 'Compare two candidate model answers and submit a rubric-backed preference.',
    qualityBar: 'Preference aligns with rubric and justification cites concrete differences.',
  },
];

export const myMockTasks: Task[] = [mockTasks[2]];

export const mockHomeSummary: HomeSummary = {
  availableCount: mockTasks.filter((task) => task.status === 'available').length,
  activeCount: myMockTasks.length,
  queuedUploads: 0,
  todayEarnings: 320,
  todayStats: {
    clipsCompleted: 3,
    labelsCompleted: 18,
    unitsCompleted: 24,
    earnings: 320,
  },
  nextAction: 'Finish the road-safety video before 9 PM.',
  readiness: [
    {
      id: 'device_attestation',
      label: 'Device attestation',
      mandatory: true,
      status: 'pass',
      detail: 'This iPhone session is trusted for Crowd Mobile V1.',
    },
    {
      id: 'consent',
      label: 'Consent',
      mandatory: true,
      status: 'pass',
      detail: 'Field data collection consent is current.',
    },
    {
      id: 'geofence',
      label: 'Geofence',
      mandatory: true,
      status: 'pass',
      detail: 'Worker is inside the approved campaign region.',
    },
    {
      id: 'certification',
      label: 'Valid certification',
      mandatory: true,
      status: 'pass',
      detail: 'Required certifications are valid. One renewal is due soon.',
    },
    {
      id: 'kit_sync',
      label: 'Kit synchronization',
      mandatory: true,
      status: 'pass',
      detail: 'Assigned kit synchronized 12 minutes ago.',
    },
    {
      id: 'battery',
      label: 'Battery',
      mandatory: true,
      status: 'pass',
      detail: 'Battery is above the campaign threshold.',
    },
    {
      id: 'storage',
      label: 'Available storage',
      mandatory: true,
      status: 'warning',
      detail: '1.8 GB free. Long video capture may require cleanup.',
    },
  ],
  edgePipeline: [
    {
      id: 'edge-qc',
      label: 'Local QC shell',
      status: 'ready',
      detail: 'Simulated focus, tilt, framing, steady, light and sync checks are available.',
    },
    {
      id: 'upload-sync',
      label: 'Upload sync',
      status: 'idle',
      detail: 'SQLite queue will retry when connectivity returns.',
    },
    {
      id: 'server-qc',
      label: 'Mock QC',
      status: 'processing',
      detail: 'Demo duplicate and QC states are mocked locally in this prototype.',
    },
  ],
};

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-cert',
    title: 'Certification expires soon',
    body: 'Visual QA Basics needs renewal within 12 days.',
    createdAt: new Date(now - 1000 * 60 * 25).toISOString(),
    read: false,
    tone: 'warning',
    deepLink: '/learn',
  },
  {
    id: 'notif-paid',
    title: 'Payout settled',
    body: 'Three approved submissions were added to your wallet ledger.',
    createdAt: new Date(now - 1000 * 60 * 60 * 5).toISOString(),
    read: true,
    tone: 'success',
    deepLink: '/wallet',
  },
];

export const mockAppeals: AppealRecord[] = [
  {
    id: 'appeal-102',
    submissionId: 'sub-road-possible-duplicate',
    ground: 'The clip was recorded from a different traffic signal angle and should be reviewed by QA.',
    state: 'with_qa',
    createdAt: new Date(now - 1000 * 60 * 60 * 8).toISOString(),
  },
];

export const mockCertifications: Certification[] = [
  {
    id: 'cert-visual',
    title: 'Visual QA Basics',
    progress: 1,
    status: 'expires_soon',
    expiresAt: new Date(now + 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: 'cert-privacy',
    title: 'Field Privacy and Consent',
    progress: 0.72,
    status: 'in_progress',
  },
  {
    id: 'cert-audio',
    title: 'Audio Capture Safety',
    progress: 0,
    status: 'not_started',
  },
  {
    id: 'cert-model-eval',
    title: 'Model Evaluation Basics',
    progress: 1,
    status: 'certified',
    expiresAt: new Date(now + 1000 * 60 * 60 * 24 * 90).toISOString(),
  },
];

export const mockLearningModules: LearningModule[] = [
  {
    id: 'module-privacy',
    title: 'Field Privacy and Consent',
    required: true,
    minutes: 18,
    progress: 0.72,
    certificationId: 'cert-privacy',
  },
  {
    id: 'module-capture-qc',
    title: 'Mobile Capture QC',
    required: true,
    minutes: 14,
    progress: 1,
    certificationId: 'cert-visual',
  },
  {
    id: 'module-appeals',
    title: 'Rejected QC and Appeals',
    required: false,
    minutes: 9,
    progress: 0.35,
  },
];

export const mockKitCustody: KitCustody = {
  kitId: 'kit-blr-1087',
  kitName: 'BLR Crowd Kit 1087',
  custodyStatus: 'accepted',
  acceptedAt: new Date(now - 1000 * 60 * 60 * 24 * 6).toISOString(),
  warnings: ['BLE, UWB, Wi-Fi Direct and USB-C service adapters are V1 shells until physical device testing is completed.'],
  devices: [
    {
      id: 'device-phone-1087',
      assetId: 'COSAARTHI-PHONE-1087',
      name: 'Worker iPhone',
      model: 'iPhone field device',
      firmware: 'iOS managed',
      battery: 0.82,
      health: 'good',
      syncStatus: 'synced',
      timeSyncOffsetMs: 42,
      connection: 'not_connected',
    },
    {
      id: 'device-camera-214',
      assetId: 'COSAARTHI-CAM-214',
      name: 'External capture camera',
      model: 'Cosaarthi Cam V2',
      firmware: '2.4.1',
      battery: 0.64,
      health: 'warning',
      syncStatus: 'pending',
      timeSyncOffsetMs: 180,
      connection: 'ble',
    },
  ],
};

export const mockWallet: WalletSummary = {
  balance: 1240,
  pending: 420,
  lifetime: 18860,
  currency: 'INR',
  weekEarnings: 1680,
  byJobType: [
    { label: 'Capture', amount: 620 },
    { label: 'Annotation', amount: 410 },
    { label: 'Transcription', amount: 280 },
    { label: 'Survey', amount: 210 },
    { label: 'SxS rating', amount: 160 },
  ],
  withdrawals: [
    {
      id: 'wd-101',
      amount: 1500,
      status: 'settled',
      createdAt: new Date(now - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
      id: 'wd-102',
      amount: 500,
      status: 'processing',
      createdAt: new Date(now - 1000 * 60 * 60 * 15).toISOString(),
    },
  ],
  ledger: [
    {
      id: 'ledger-1',
      label: 'Storefront image set',
      amount: 180,
      status: 'settled',
      createdAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
    },
    {
      id: 'ledger-2',
      label: 'Road-safety review',
      amount: 260,
      status: 'pending',
      createdAt: new Date(now - 1000 * 60 * 60 * 20).toISOString(),
    },
    {
      id: 'ledger-3',
      label: 'Shelf image labels',
      amount: 95,
      status: 'settled',
      createdAt: new Date(now - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
  ],
};
