"""Fix 9 — the client is visible to the partner that bids to it.

The mirror of Fix 4. Hand-written, not autogenerated: alembic does not see RLS
policies, which is what this revision consists of. Keep it byte-for-byte in step
with the Fix 9 block at the end of db/110_auth_functions.sql — the two paths
diverging is the failure mode 0001's docstring exists to warn about.

Revision ID: 0004
Revises: 0003
"""

from alembic import op

revision = "0004"
down_revision = "0003"

VISIBILITY_FN = """
CREATE OR REPLACE FUNCTION org_visible_via_my_proposal(p_org_id uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM request r
    JOIN proposal p ON p.request_id = r.id
    WHERE r.client_org_id = p_org_id
      AND p.partner_org_id = current_org_id()
      AND p.deleted_at IS NULL
  )
$fn$;
"""


def upgrade() -> None:
    op.execute(VISIBILITY_FN)
    op.execute("REVOKE EXECUTE ON FUNCTION org_visible_via_my_proposal(uuid) FROM PUBLIC")
    op.execute(
        "GRANT EXECUTE ON FUNCTION org_visible_via_my_proposal(uuid) "
        "TO sourcehub_app, sourcehub_readonly"
    )
    op.execute(
        "CREATE POLICY organisation_select_my_clients ON organisation FOR SELECT "
        "USING (org_visible_via_my_proposal(id))"
    )
    op.execute(
        "CREATE POLICY client_profile_select_my_clients ON client_profile FOR SELECT "
        "USING (org_visible_via_my_proposal(org_id))"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS client_profile_select_my_clients ON client_profile")
    op.execute("DROP POLICY IF EXISTS organisation_select_my_clients ON organisation")
    op.execute("DROP FUNCTION IF EXISTS org_visible_via_my_proposal(uuid)")
