"""Client-supplied storage destinations.

Captures stop landing in SourceHub's bucket and start landing in the client's,
named on the request. Hand-written rather than autogenerated: alembic sees
neither the RLS policies nor the SECURITY DEFINER resolvers, and those are half
of what this revision is. Keep it byte-for-byte in step with db/035_storage.sql,
the storage blocks in db/100_rls.sql and Fix 10 at the end of
db/110_auth_functions.sql — the two paths diverging is the failure mode 0001's
docstring exists to warn about.

Ordering note: the new columns are nullable and backfilled to a legacy target
pointing at platform storage, so existing requests and contracts keep working
and existing assets keep resolving. The API requires a destination for new
work; the database does not, because it cannot invent one for rows already
here.

Revision ID: 0005
Revises: 0004
"""

from alembic import op

revision = "0005"
down_revision = "0004"


TABLE = """
CREATE TABLE storage_target (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_org_id  uuid NOT NULL REFERENCES organisation(id) ON DELETE RESTRICT,

  label         text NOT NULL,
  provider      storage_provider NOT NULL,
  endpoint      text,
  region        text,
  bucket        text NOT NULL,
  key_prefix    text NOT NULL DEFAULT '',

  secret        jsonb NOT NULL,

  verified_at   timestamptz,
  verify_error  text,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid REFERENCES app_user(id),
  updated_by    uuid REFERENCES app_user(id),
  deleted_at    timestamptz,

  CONSTRAINT storage_target_prefix_shape
    CHECK (key_prefix = '' OR key_prefix ~ '^[A-Za-z0-9._/-]+/$')
);
"""

RESOLVERS = """
CREATE OR REPLACE FUNCTION storage_destination_for_contract(p_contract uuid)
RETURNS storage_target
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT st.* FROM storage_target st
  JOIN contract c ON c.storage_target_id = st.id
  WHERE c.id = p_contract AND st.deleted_at IS NULL
$fn$;

CREATE OR REPLACE FUNCTION storage_destination_by_id(p_target uuid)
RETURNS storage_target
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT st.* FROM storage_target st
  WHERE st.id = p_target AND st.deleted_at IS NULL
$fn$;
"""


def upgrade() -> None:
    op.execute("CREATE TYPE storage_provider AS ENUM ('s3','gcs','azure_blob')")
    op.execute(TABLE)
    op.execute(
        "CREATE INDEX storage_target_owner_idx ON storage_target (owner_org_id) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX storage_target_label_key "
        "ON storage_target (owner_org_id, lower(label)) WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE TRIGGER storage_target_updated_at BEFORE UPDATE ON storage_target "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )

    op.execute("ALTER TABLE request  ADD COLUMN storage_target_id uuid REFERENCES storage_target(id)")
    op.execute("ALTER TABLE contract ADD COLUMN storage_target_id uuid REFERENCES storage_target(id)")
    op.execute("ALTER TABLE asset    ADD COLUMN storage_target_id uuid REFERENCES storage_target(id)")

    # RLS. A destination never leaves the client that supplied it.
    op.execute("ALTER TABLE storage_target ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE storage_target FORCE  ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY storage_target_select ON storage_target FOR SELECT "
        "USING (is_platform_admin() OR owner_org_id = current_org_id())"
    )
    op.execute(
        "CREATE POLICY storage_target_insert ON storage_target FOR INSERT "
        "WITH CHECK (owner_org_id = current_org_id())"
    )
    op.execute(
        "CREATE POLICY storage_target_update ON storage_target FOR UPDATE "
        "USING      (is_platform_admin() OR owner_org_id = current_org_id()) "
        "WITH CHECK (is_platform_admin() OR owner_org_id = current_org_id())"
    )
    op.execute(
        "CREATE POLICY storage_target_worker_deny ON storage_target AS RESTRICTIVE FOR ALL "
        "USING (NOT is_worker()) WITH CHECK (NOT is_worker())"
    )

    op.execute(RESOLVERS)
    op.execute("REVOKE EXECUTE ON FUNCTION storage_destination_for_contract(uuid) FROM PUBLIC")
    op.execute("REVOKE EXECUTE ON FUNCTION storage_destination_by_id(uuid)        FROM PUBLIC")
    # sourcehub_app only: unlike the other definer functions these return
    # credential material, and the read-only role exists for analytics.
    op.execute("GRANT EXECUTE ON FUNCTION storage_destination_for_contract(uuid) TO sourcehub_app")
    op.execute("GRANT EXECUTE ON FUNCTION storage_destination_by_id(uuid)        TO sourcehub_app")

    op.execute(
        "INSERT INTO permission (code, module, description, requires_mfa) "
        "VALUES ('storage.manage','storage','Manage where captured data is delivered',false) "
        "ON CONFLICT (code) DO NOTHING"
    )
    op.execute(
        "INSERT INTO role_permission (role_id, permission_id) "
        "SELECT r.id, p.id FROM role r, permission p "
        "WHERE r.code = 'client' AND p.code = 'storage.manage' "
        "ON CONFLICT DO NOTHING"
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_permission WHERE permission_id IN "
        "(SELECT id FROM permission WHERE code = 'storage.manage')"
    )
    op.execute("DELETE FROM permission WHERE code = 'storage.manage'")
    op.execute("DROP FUNCTION IF EXISTS storage_destination_for_contract(uuid)")
    op.execute("DROP FUNCTION IF EXISTS storage_destination_by_id(uuid)")
    op.execute("ALTER TABLE asset    DROP COLUMN IF EXISTS storage_target_id")
    op.execute("ALTER TABLE contract DROP COLUMN IF EXISTS storage_target_id")
    op.execute("ALTER TABLE request  DROP COLUMN IF EXISTS storage_target_id")
    op.execute("DROP TABLE IF EXISTS storage_target")
    op.execute("DROP TYPE IF EXISTS storage_provider")
