"""Attachments — files hung off a field.

Hand-written, not autogenerated: alembic sees neither the RLS policies nor the
SECURITY INVOKER visibility function, and those are most of what this is. Keep
it byte-for-byte in step with db/095_attachments.sql, the attachment block in
db/100_rls.sql, and the two worker policies at the end of
db/120_workers_media.sql.

Purely additive — a new type, a new table and its policies. Nothing existing
changes, so there is no backfill and downgrade is a clean drop.

Revision ID: 0006
Revises: 0005
"""

from alembic import op

revision = "0006"
down_revision = "0005"


TABLE = """
CREATE TABLE attachment (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  entity_type   attachment_entity NOT NULL,
  entity_id     uuid NOT NULL,
  slot          text NOT NULL,

  owner_org_id  uuid NOT NULL REFERENCES organisation(id) ON DELETE RESTRICT,

  filename      text NOT NULL,
  storage_key   text NOT NULL UNIQUE,
  content_type  text,
  size_bytes    bigint NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 26214400),

  uploaded_by   uuid REFERENCES app_user(id),
  uploaded_at   timestamptz NOT NULL DEFAULT now(),
  deleted_at    timestamptz,

  CONSTRAINT attachment_slot_shape CHECK (slot ~ '^[a-z][a-z0-9_]{0,39}$')
);
"""

VISIBILITY = """
CREATE OR REPLACE FUNCTION attachment_parent_visible(p_type attachment_entity, p_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public AS $fn$
  SELECT CASE p_type
    WHEN 'request'   THEN EXISTS (SELECT 1 FROM request   WHERE id = p_id AND deleted_at IS NULL)
    WHEN 'proposal'  THEN EXISTS (SELECT 1 FROM proposal  WHERE id = p_id AND deleted_at IS NULL)
    WHEN 'task'      THEN EXISTS (SELECT 1 FROM task      WHERE id = p_id AND deleted_at IS NULL)
    WHEN 'qa_review' THEN EXISTS (SELECT 1 FROM qa_review WHERE id = p_id)
    ELSE false
  END
$fn$;
"""


def upgrade() -> None:
    op.execute("CREATE TYPE attachment_entity AS ENUM ('request','proposal','task','qa_review')")
    op.execute(TABLE)
    op.execute(
        "CREATE INDEX attachment_entity_idx ON attachment (entity_type, entity_id) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX attachment_owner_idx ON attachment (owner_org_id) WHERE deleted_at IS NULL"
    )
    op.execute(VISIBILITY)

    op.execute("ALTER TABLE attachment ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE attachment FORCE  ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY attachment_select ON attachment FOR SELECT USING ("
        "  is_platform_admin() OR owner_org_id = current_org_id() "
        "  OR attachment_parent_visible(entity_type, entity_id))"
    )
    op.execute(
        "CREATE POLICY attachment_insert ON attachment FOR INSERT "
        "WITH CHECK (owner_org_id = current_org_id())"
    )
    op.execute(
        "CREATE POLICY attachment_update ON attachment FOR UPDATE "
        "USING      (is_platform_admin() OR owner_org_id = current_org_id()) "
        "WITH CHECK (is_platform_admin() OR owner_org_id = current_org_id())"
    )
    # Read is deliberately not denied to workers: a task's attachment is the
    # shot list, and the phone is who needs it.
    op.execute(
        "CREATE POLICY attachment_worker_no_insert ON attachment AS RESTRICTIVE "
        "FOR INSERT WITH CHECK (NOT is_worker())"
    )
    op.execute(
        "CREATE POLICY attachment_worker_no_update ON attachment AS RESTRICTIVE "
        "FOR UPDATE USING (NOT is_worker()) WITH CHECK (NOT is_worker())"
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS attachment_parent_visible(attachment_entity, uuid)")
    op.execute("DROP TABLE IF EXISTS attachment")
    op.execute("DROP TYPE IF EXISTS attachment_entity")
