"""The folder a file belongs in: client name and RFP reference.

Platform storage moved from MinIO to Azure Blob and gained a human-readable
layout — one folder per client, one per RFP inside it. Computing that path needs
a name and a reference code that the attaching party frequently cannot see: a
partner attaches a method statement to the CLIENT's folder.

Hand-written, not autogenerated: alembic does not see SECURITY DEFINER
functions. Keep it byte-for-byte in step with Fix 11 at the end of
db/110_auth_functions.sql.

Revision ID: 0007
Revises: 0006
"""

from alembic import op

revision = "0007"
down_revision = "0006"


FOLDER_FN = """
CREATE OR REPLACE FUNCTION attachment_folder(p_type attachment_entity, p_id uuid)
RETURNS TABLE (client_name text, request_ref text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT o.name, r.reference_code
  FROM   request r
  JOIN   organisation o ON o.id = r.client_org_id
  WHERE  r.id = CASE p_type
    WHEN 'request'   THEN p_id
    WHEN 'proposal'  THEN (SELECT p.request_id FROM proposal p WHERE p.id = p_id)
    WHEN 'task'      THEN (SELECT c.request_id FROM task t
                            JOIN contract c ON c.id = t.contract_id
                           WHERE t.id = p_id)
    WHEN 'qa_review' THEN (SELECT c.request_id FROM qa_review q
                            JOIN submission s ON s.id = q.submission_id
                            JOIN task t       ON t.id = s.task_id
                            JOIN contract c   ON c.id = t.contract_id
                           WHERE q.id = p_id)
  END
$fn$;
"""


def upgrade() -> None:
    op.execute(FOLDER_FN)
    op.execute("REVOKE EXECUTE ON FUNCTION attachment_folder(attachment_entity, uuid) FROM PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION attachment_folder(attachment_entity, uuid) TO sourcehub_app")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS attachment_folder(attachment_entity, uuid)")
